"use strict";

export default {
  "admitting": [
    {
      "id": "1",
      "diagnosisID": "3",
      "hospitalID": "NULL",
      "doctorID": "1",
      "date": "2016-04-03 16:00:00",
      "roomAssigned": "12",
      "erOrClinic": "er",
      "pay": "hmo",
      "surgery": "2016-04-04 02:00:00",
      "deleted_at": "NULL",
      "created_at": "2016-03-28 19:01:42",
      "updated_at": "2016-03-28 22:45:43"
    },
    {
      "id": "2",
      "diagnosisID": "5",
      "hospitalID": "NULL",
      "doctorID": "1",
      "date": "2016-04-03 16:00:00",
      "roomAssigned": "12",
      "erOrClinic": "new",
      "pay": "charity",
      "surgery": "2016-04-03 01:00:00",
      "deleted_at": "NULL",
      "created_at": "2016-04-03 18:37:56",
      "updated_at": "2016-04-03 18:37:56"
    },
    {
      "id": "3",
      "diagnosisID": "6",
      "hospitalID": "NULL",
      "doctorID": "1",
      "date": "2016-04-04 16:00:00",
      "roomAssigned": "311",
      "erOrClinic": "new",
      "pay": "personal",
      "surgery": "2016-04-04 22:41:05",
      "deleted_at": "2016-04-04 22:41:19",
      "created_at": "2016-04-04 22:39:50",
      "updated_at": "2016-04-04 22:41:19"
    },
    {
      "id": "4",
      "diagnosisID": "6",
      "hospitalID": "NULL",
      "doctorID": "1",
      "date": "2016-04-04 16:00:00",
      "roomAssigned": "311",
      "erOrClinic": "elective",
      "pay": "charity",
      "surgery": "2016-04-04 22:41:39",
      "deleted_at": "2016-04-04 22:41:55",
      "created_at": "2016-04-04 22:41:39",
      "updated_at": "2016-04-04 22:41:55"
    },
    {
      "id": "5",
      "diagnosisID": "6",
      "hospitalID": "NULL",
      "doctorID": "1",
      "date": "2016-04-04 16:00:00",
      "roomAssigned": "311",
      "erOrClinic": "elective",
      "pay": "personal",
      "surgery": "2016-04-04 22:42:36",
      "deleted_at": "NULL",
      "created_at": "2016-04-04 22:42:36",
      "updated_at": "2016-04-04 22:42:36"
    },
    {
      "id": "6",
      "diagnosisID": "7",
      "hospitalID": "NULL",
      "doctorID": "1",
      "date": "2016-04-04 16:00:00",
      "roomAssigned": "421",
      "erOrClinic": "new",
      "pay": "charity",
      "surgery": "2016-04-04 23:13:06",
      "deleted_at": "2016-04-04 23:13:13",
      "created_at": "2016-04-04 23:13:06",
      "updated_at": "2016-04-04 23:13:13"
    },
    {
      "id": "7",
      "diagnosisID": "7",
      "hospitalID": "NULL",
      "doctorID": "1",
      "date": "2016-04-04 16:00:00",
      "roomAssigned": "",
      "erOrClinic": "new",
      "pay": "charity",
      "surgery": "2016-04-04 23:14:55",
      "deleted_at": "2016-04-04 23:15:35",
      "created_at": "2016-04-04 23:14:55",
      "updated_at": "2016-04-04 23:15:35"
    },
    {
      "id": "8",
      "diagnosisID": "7",
      "hospitalID": "NULL",
      "doctorID": "1",
      "date": "2016-04-04 16:00:00",
      "roomAssigned": "312",
      "erOrClinic": "elective",
      "pay": "personal",
      "surgery": "2016-04-05 23:43:00",
      "deleted_at": "2016-04-05 00:05:26",
      "created_at": "2016-04-04 23:43:14",
      "updated_at": "2016-04-05 00:05:26"
    },
    {
      "id": "9",
      "diagnosisID": "10",
      "hospitalID": "NULL",
      "doctorID": "1",
      "date": "2016-05-02 16:00:00",
      "roomAssigned": "314",
      "erOrClinic": "new",
      "pay": "charity",
      "surgery": "2016-05-03 00:47:00",
      "deleted_at": "NULL",
      "created_at": "2016-05-03 00:47:55",
      "updated_at": "2016-05-03 00:48:27"
    }
  ],
  "appointments": [
    {
      "id": "2",
      "doctorID": "1",
      "patientID": "5",
      "staffID": "NULL",
      "userID": "NULL",
      "hospitalID": "NULL",
      "type": "follow-up",
      "date": "2016-03-28",
      "timeStart": "08:00:00",
      "timeEnd": "08:15:00",
      "notes": "NULL",
      "occured": "NULL",
      "reminder": "NULL",
      "reminderSent": "NULL",
      "roomAssignment": "NULL",
      "deleted_at": "NULL",
      "created_at": "2016-03-28 00:54:31",
      "updated_at": "2016-03-28 00:54:31"
    },
    {
      "id": "3",
      "doctorID": "1",
      "patientID": "5",
      "staffID": "NULL",
      "userID": "NULL",
      "hospitalID": "NULL",
      "type": "follow-up",
      "date": "2016-04-11",
      "timeStart": "09:15:00",
      "timeEnd": "09:45:00",
      "notes": "with companion",
      "occured": "NULL",
      "reminder": "NULL",
      "reminderSent": "NULL",
      "roomAssignment": "NULL",
      "deleted_at": "NULL",
      "created_at": "2016-03-28 19:16:02",
      "updated_at": "2016-03-28 19:16:09"
    },
    {
      "id": "4",
      "doctorID": "1",
      "patientID": "3",
      "staffID": "NULL",
      "userID": "NULL",
      "hospitalID": "NULL",
      "type": "follow-up",
      "date": "2016-03-31",
      "timeStart": "08:00:00",
      "timeEnd": "08:15:00",
      "notes": "NULL",
      "occured": "NULL",
      "reminder": "NULL",
      "reminderSent": "NULL",
      "roomAssignment": "NULL",
      "deleted_at": "NULL",
      "created_at": "2016-03-31 01:19:48",
      "updated_at": "2016-03-31 01:19:48"
    },
    {
      "id": "5",
      "doctorID": "1",
      "patientID": "3",
      "staffID": "NULL",
      "userID": "NULL",
      "hospitalID": "NULL",
      "type": "follow-up",
      "date": "2016-04-04",
      "timeStart": "08:00:00",
      "timeEnd": "08:15:00",
      "notes": "NULL",
      "occured": "NULL",
      "reminder": "NULL",
      "reminderSent": "NULL",
      "roomAssignment": "NULL",
      "deleted_at": "NULL",
      "created_at": "2016-04-03 18:28:40",
      "updated_at": "2016-04-03 18:28:40"
    },
    {
      "id": "6",
      "doctorID": "1",
      "patientID": "3",
      "staffID": "NULL",
      "userID": "NULL",
      "hospitalID": "NULL",
      "type": "follow-up",
      "date": "2016-04-11",
      "timeStart": "11:45:00",
      "timeEnd": "12:15:00",
      "notes": "bring results",
      "occured": "NULL",
      "reminder": "NULL",
      "reminderSent": "NULL",
      "roomAssignment": "NULL",
      "deleted_at": "NULL",
      "created_at": "2016-04-03 18:40:00",
      "updated_at": "2016-04-03 18:40:05"
    },
    {
      "id": "7",
      "doctorID": "1",
      "patientID": "7",
      "staffID": "NULL",
      "userID": "NULL",
      "hospitalID": "NULL",
      "type": "follow-up",
      "date": "2016-04-07",
      "timeStart": "11:30:00",
      "timeEnd": "12:00:00",
      "notes": "Check response of patient to meds.",
      "occured": "NULL",
      "reminder": "NULL",
      "reminderSent": "NULL",
      "roomAssignment": "NULL",
      "deleted_at": "NULL",
      "created_at": "2016-04-03 23:28:15",
      "updated_at": "2016-04-05 00:22:11"
    },
    {
      "id": "8",
      "doctorID": "2",
      "patientID": "5",
      "staffID": "NULL",
      "userID": "NULL",
      "hospitalID": "NULL",
      "type": "unspecified",
      "date": "2016-04-04",
      "timeStart": "09:30:00",
      "timeEnd": "09:45:00",
      "notes": "NULL",
      "occured": "NULL",
      "reminder": "NULL",
      "reminderSent": "NULL",
      "roomAssignment": "NULL",
      "deleted_at": "NULL",
      "created_at": "2016-04-04 00:22:48",
      "updated_at": "2016-04-04 00:22:48"
    },
    {
      "id": "9",
      "doctorID": "1",
      "patientID": "2",
      "staffID": "NULL",
      "userID": "NULL",
      "hospitalID": "NULL",
      "type": "follow-up",
      "date": "2016-04-04",
      "timeStart": "08:00:00",
      "timeEnd": "08:15:00",
      "notes": "NULL",
      "occured": "NULL",
      "reminder": "NULL",
      "reminderSent": "NULL",
      "roomAssignment": "NULL",
      "deleted_at": "NULL",
      "created_at": "2016-04-04 01:59:11",
      "updated_at": "2016-04-04 01:59:11"
    },
    {
      "id": "10",
      "doctorID": "1",
      "patientID": "4",
      "staffID": "NULL",
      "userID": "NULL",
      "hospitalID": "NULL",
      "type": "follow-up",
      "date": "2016-04-04",
      "timeStart": "08:00:00",
      "timeEnd": "08:15:00",
      "notes": "NULL",
      "occured": "NULL",
      "reminder": "NULL",
      "reminderSent": "NULL",
      "roomAssignment": "NULL",
      "deleted_at": "NULL",
      "created_at": "2016-04-04 01:59:33",
      "updated_at": "2016-04-04 01:59:33"
    },
    {
      "id": "11",
      "doctorID": "1",
      "patientID": "4",
      "staffID": "NULL",
      "userID": "NULL",
      "hospitalID": "NULL",
      "type": "admission",
      "date": "2016-04-04",
      "timeStart": "08:00:00",
      "timeEnd": "08:15:00",
      "notes": "NULL",
      "occured": "NULL",
      "reminder": "NULL",
      "reminderSent": "NULL",
      "roomAssignment": "NULL",
      "deleted_at": "2016-04-04 02:00:54",
      "created_at": "2016-04-04 01:59:50",
      "updated_at": "2016-04-04 02:00:54"
    },
    {
      "id": "12",
      "doctorID": "1",
      "patientID": "3",
      "staffID": "NULL",
      "userID": "NULL",
      "hospitalID": "NULL",
      "type": "follow-up",
      "date": "2016-04-04",
      "timeStart": "09:00:00",
      "timeEnd": "09:15:00",
      "notes": "NULL",
      "occured": "NULL",
      "reminder": "NULL",
      "reminderSent": "NULL",
      "roomAssignment": "NULL",
      "deleted_at": "NULL",
      "created_at": "2016-04-04 02:00:09",
      "updated_at": "2016-04-04 02:00:09"
    },
    {
      "id": "13",
      "doctorID": "1",
      "patientID": "7",
      "staffID": "NULL",
      "userID": "NULL",
      "hospitalID": "NULL",
      "type": "follow-up",
      "date": "2016-04-07",
      "timeStart": "12:00:00",
      "timeEnd": "12:30:00",
      "notes": "test",
      "occured": "NULL",
      "reminder": "NULL",
      "reminderSent": "NULL",
      "roomAssignment": "NULL",
      "deleted_at": "NULL",
      "created_at": "2016-04-04 17:40:12",
      "updated_at": "2016-04-06 00:50:23"
    },
    {
      "id": "14",
      "doctorID": "1",
      "patientID": "7",
      "staffID": "NULL",
      "userID": "NULL",
      "hospitalID": "NULL",
      "type": "follow-up",
      "date": "2016-04-07",
      "timeStart": "12:00:00",
      "timeEnd": "12:30:00",
      "notes": "testing",
      "occured": "NULL",
      "reminder": "NULL",
      "reminderSent": "NULL",
      "roomAssignment": "NULL",
      "deleted_at": "2016-04-04 17:41:39",
      "created_at": "2016-04-04 17:40:48",
      "updated_at": "2016-04-04 17:41:39"
    },
    {
      "id": "15",
      "doctorID": "1",
      "patientID": "5",
      "staffID": "NULL",
      "userID": "NULL",
      "hospitalID": "NULL",
      "type": "follow-up",
      "date": "2016-04-07",
      "timeStart": "13:15:00",
      "timeEnd": "13:45:00",
      "notes": "",
      "occured": "NULL",
      "reminder": "NULL",
      "reminderSent": "NULL",
      "roomAssignment": "NULL",
      "deleted_at": "2016-04-04 23:17:55",
      "created_at": "2016-04-04 17:57:10",
      "updated_at": "2016-04-04 23:17:55"
    },
    {
      "id": "16",
      "doctorID": "1",
      "patientID": "7",
      "staffID": "NULL",
      "userID": "NULL",
      "hospitalID": "NULL",
      "type": "follow-up",
      "date": "2016-04-07",
      "timeStart": "16:15:00",
      "timeEnd": "16:45:00",
      "notes": "",
      "occured": "NULL",
      "reminder": "NULL",
      "reminderSent": "NULL",
      "roomAssignment": "NULL",
      "deleted_at": "NULL",
      "created_at": "2016-04-04 17:58:30",
      "updated_at": "2016-04-06 00:50:43"
    },
    {
      "id": "17",
      "doctorID": "1",
      "patientID": "5",
      "staffID": "NULL",
      "userID": "NULL",
      "hospitalID": "NULL",
      "type": "follow-up",
      "date": "2016-04-07",
      "timeStart": "08:00:00",
      "timeEnd": "08:15:00",
      "notes": "NULL",
      "occured": "NULL",
      "reminder": "NULL",
      "reminderSent": "NULL",
      "roomAssignment": "NULL",
      "deleted_at": "NULL",
      "created_at": "2016-04-04 18:31:03",
      "updated_at": "2016-04-04 18:31:03"
    },
    {
      "id": "18",
      "doctorID": "1",
      "patientID": "5",
      "staffID": "NULL",
      "userID": "NULL",
      "hospitalID": "NULL",
      "type": "follow-up",
      "date": "2016-04-07",
      "timeStart": "13:15:00",
      "timeEnd": "13:30:00",
      "notes": "NULL",
      "occured": "NULL",
      "reminder": "NULL",
      "reminderSent": "NULL",
      "roomAssignment": "NULL",
      "deleted_at": "NULL",
      "created_at": "2016-04-04 18:31:44",
      "updated_at": "2016-04-04 18:31:44"
    },
    {
      "id": "19",
      "doctorID": "1",
      "patientID": "7",
      "staffID": "NULL",
      "userID": "NULL",
      "hospitalID": "NULL",
      "type": "follow-up",
      "date": "2016-04-07",
      "timeStart": "09:00:00",
      "timeEnd": "09:15:00",
      "notes": "NULL",
      "occured": "NULL",
      "reminder": "NULL",
      "reminderSent": "NULL",
      "roomAssignment": "NULL",
      "deleted_at": "NULL",
      "created_at": "2016-04-06 00:51:40",
      "updated_at": "2016-04-06 00:51:40"
    },
    {
      "id": "20",
      "doctorID": "1",
      "patientID": "9",
      "staffID": "NULL",
      "userID": "NULL",
      "hospitalID": "NULL",
      "type": "unspecified",
      "date": "2016-04-22",
      "timeStart": "16:00:00",
      "timeEnd": "16:30:00",
      "notes": "NULL",
      "occured": "NULL",
      "reminder": "NULL",
      "reminderSent": "NULL",
      "roomAssignment": "NULL",
      "deleted_at": "2016-04-14 23:43:55",
      "created_at": "2016-04-14 23:26:31",
      "updated_at": "2016-04-14 23:43:55"
    },
    {
      "id": "21",
      "doctorID": "1",
      "patientID": "9",
      "staffID": "NULL",
      "userID": "NULL",
      "hospitalID": "NULL",
      "type": "follow-up",
      "date": "2016-04-15",
      "timeStart": "16:00:00",
      "timeEnd": "17:00:00",
      "notes": "NULL",
      "occured": "NULL",
      "reminder": "NULL",
      "reminderSent": "NULL",
      "roomAssignment": "NULL",
      "deleted_at": "NULL",
      "created_at": "2016-04-14 23:47:06",
      "updated_at": "2016-04-14 23:47:06"
    },
    {
      "id": "22",
      "doctorID": "1",
      "patientID": "10",
      "staffID": "NULL",
      "userID": "NULL",
      "hospitalID": "NULL",
      "type": "follow-up",
      "date": "2016-05-05",
      "timeStart": "08:45:00",
      "timeEnd": "09:15:00",
      "notes": "",
      "occured": "NULL",
      "reminder": "NULL",
      "reminderSent": "NULL",
      "roomAssignment": "NULL",
      "deleted_at": "2016-05-03 17:36:19",
      "created_at": "2016-05-03 00:54:16",
      "updated_at": "2016-05-03 17:36:19"
    },
    {
      "id": "23",
      "doctorID": "1",
      "patientID": "9",
      "staffID": "NULL",
      "userID": "NULL",
      "hospitalID": "NULL",
      "type": "follow-up",
      "date": "2016-05-04",
      "timeStart": "08:00:00",
      "timeEnd": "08:15:00",
      "notes": "NULL",
      "occured": "NULL",
      "reminder": "NULL",
      "reminderSent": "NULL",
      "roomAssignment": "NULL",
      "deleted_at": "NULL",
      "created_at": "2016-05-03 17:35:15",
      "updated_at": "2016-05-03 17:35:15"
    },
    {
      "id": "24",
      "doctorID": "1",
      "patientID": "11",
      "staffID": "NULL",
      "userID": "NULL",
      "hospitalID": "NULL",
      "type": "follow-up",
      "date": "2016-05-06",
      "timeStart": "09:00:00",
      "timeEnd": "09:30:00",
      "notes": "",
      "occured": "NULL",
      "reminder": "NULL",
      "reminderSent": "NULL",
      "roomAssignment": "NULL",
      "deleted_at": "NULL",
      "created_at": "2016-05-03 17:51:15",
      "updated_at": "2016-05-03 17:53:41"
    },
    {
      "id": "25",
      "doctorID": "1",
      "patientID": "5",
      "staffID": "NULL",
      "userID": "NULL",
      "hospitalID": "NULL",
      "type": "follow-up",
      "date": "2016-05-04",
      "timeStart": "14:45:00",
      "timeEnd": "15:00:00",
      "notes": "NULL",
      "occured": "NULL",
      "reminder": "NULL",
      "reminderSent": "NULL",
      "roomAssignment": "NULL",
      "deleted_at": "NULL",
      "created_at": "2016-05-03 17:55:55",
      "updated_at": "2016-05-03 17:55:55"
    },
    {
      "id": "26",
      "doctorID": "1",
      "patientID": "5",
      "staffID": "NULL",
      "userID": "NULL",
      "hospitalID": "NULL",
      "type": "follow-up",
      "date": "2016-05-06",
      "timeStart": "09:00:00",
      "timeEnd": "09:15:00",
      "notes": "NULL",
      "occured": "NULL",
      "reminder": "NULL",
      "reminderSent": "NULL",
      "roomAssignment": "NULL",
      "deleted_at": "NULL",
      "created_at": "2016-05-03 17:56:32",
      "updated_at": "2016-05-03 17:56:32"
    },
    {
      "id": "27",
      "doctorID": "NULL",
      "patientID": "5",
      "staffID": "NULL",
      "userID": "NULL",
      "hospitalID": "NULL",
      "type": "follow-up",
      "date": "2016-05-05",
      "timeStart": "08:00:00",
      "timeEnd": "08:15:00",
      "notes": "NULL",
      "occured": "NULL",
      "reminder": "NULL",
      "reminderSent": "NULL",
      "roomAssignment": "NULL",
      "deleted_at": "NULL",
      "created_at": "2016-05-04 19:36:24",
      "updated_at": "2016-05-04 19:36:24"
    },
    {
      "id": "28",
      "doctorID": "NULL",
      "patientID": "5",
      "staffID": "NULL",
      "userID": "NULL",
      "hospitalID": "NULL",
      "type": "follow-up",
      "date": "2016-05-05",
      "timeStart": "09:00:00",
      "timeEnd": "09:15:00",
      "notes": "NULL",
      "occured": "NULL",
      "reminder": "NULL",
      "reminderSent": "NULL",
      "roomAssignment": "NULL",
      "deleted_at": "NULL",
      "created_at": "2016-05-04 19:37:04",
      "updated_at": "2016-05-04 19:37:04"
    },
    {
      "id": "29",
      "doctorID": "1",
      "patientID": "5",
      "staffID": "NULL",
      "userID": "NULL",
      "hospitalID": "NULL",
      "type": "follow-up",
      "date": "2016-05-30",
      "timeStart": "08:00:00",
      "timeEnd": "08:15:00",
      "notes": "NULL",
      "occured": "NULL",
      "reminder": "NULL",
      "reminderSent": "NULL",
      "roomAssignment": "NULL",
      "deleted_at": "NULL",
      "created_at": "2016-05-29 23:21:07",
      "updated_at": "2016-05-29 23:21:07"
    }
  ],
  "bmiRecords": [],
  "cache": [],
  "cptCategories": [],
  "diagnosis": [
  {
    "id": "1",
    "patientID": "2",
    "doctorID": "1",
    "appointmentID": null,
    "preparedByID": null,
    "chiefComplaint": "The patient comes to the clinic complaining of two days of severe diarrhea and vomiting.",
    "historyIllness": "The patient is a 41-year-old male who comes in for a consultation.",
    "bodyTemperature": "37.5",
    "bloodPressure": "120/90",
    "respirationRate": "18",
    "pulseRate": "80",
    "medicalHistory": "The patient has no past medical history. ",
    "initialDiagnosis": "Bacterial Gastroenteritis",
    "physicalExam": "",
    "services": "Adult",
    "type": "Consult",
    "code": "Gastro Intestinal Track",
    "category": null,
    "plan": "CBC\r\nStool Exam\r\nOral rehydration\r\nAntimotility medicine",
    "pay": "hmo",
    "referringDoctor": null,
    "labs": "",
    "imaging": "",
    "accident": "0",
    "painLevel": "1",
    "allergies": "No patient allergies",
    "currentMedications": "Lomotil",
    "date": "2016-03-23",
    "timeStart": "04:36:00",
    "timeEnd": null,
    "certRemarks": "Bacterial Gastroenteritis",
    "certPurpose": "Fit to work",
    "deleted_at": null,
    "created_at": "2016-03-23 04:47:43",
    "updated_at": "2016-03-23 05:28:08"
  },
  {
    "id": "2",
    "patientID": "3",
    "doctorID": "1",
    "appointmentID": null,
    "preparedByID": null,
    "chiefComplaint": "vomiting, abdominal pain and loose bowel movements ",
    "historyIllness": "The patient came to the clinic today due to severe vomiting, abdominal pain and loose bowel movements ",
    "bodyTemperature": "37.4",
    "bloodPressure": "130/80",
    "respirationRate": "16",
    "pulseRate": "75",
    "medicalHistory": "The patient has had asthma when he was a child",
    "initialDiagnosis": "Bacterial Gastroenteritis",
    "physicalExam": "",
    "services": "Adult",
    "type": "Consult",
    "code": "Medical",
    "category": null,
    "plan": "Antibiotics etc",
    "pay": "hmo",
    "referringDoctor": null,
    "labs": "",
    "imaging": "",
    "accident": "0",
    "painLevel": "1",
    "allergies": "The patient has no drug or food allergies.",
    "currentMedications": "",
    "date": "2016-03-28",
    "timeStart": "09:40:00",
    "timeEnd": null,
    "certRemarks": null,
    "certPurpose": null,
    "deleted_at": null,
    "created_at": "2016-03-28 09:45:57",
    "updated_at": "2016-03-28 09:45:57"
  },
  {
    "id": "3",
    "patientID": "5",
    "doctorID": "3",
    "appointmentID": null,
    "preparedByID": null,
    "chiefComplaint": "wheezes DOB",
    "historyIllness": "The patient feels tired all day with occasional wheezes",
    "bodyTemperature": "37",
    "bloodPressure": "120/70",
    "respirationRate": "15",
    "pulseRate": "75",
    "medicalHistory": "asthma on mother's side",
    "initialDiagnosis": "bronchial asthma",
    "physicalExam": "",
    "services": "Adult",
    "type": "Consult",
    "code": "Medical",
    "category": null,
    "plan": "Seretide two puffs a day, 1-0-1",
    "pay": "insurance",
    "referringDoctor": null,
    "labs": "",
    "imaging": "",
    "accident": "1",
    "painLevel": "10",
    "allergies": "no known drug allergies",
    "currentMedications": "",
    "date": "2016-03-29",
    "timeStart": "01:11:00",
    "timeEnd": null,
    "certRemarks": "The patient was advised to rest with medications.",
    "certPurpose": "Fit to work",
    "deleted_at": null,
    "created_at": "2016-03-29 01:13:15",
    "updated_at": "2016-03-29 05:43:35"
  },
  {
    "id": "4",
    "patientID": "4",
    "doctorID": "2",
    "appointmentID": null,
    "preparedByID": null,
    "chiefComplaint": "DOB palpitations high BP for two days now",
    "historyIllness": "The patient comes to the clinic with the above complaints",
    "bodyTemperature": "37",
    "bloodPressure": "145/100",
    "respirationRate": "19",
    "pulseRate": "90",
    "medicalHistory": "cardiovascular problems in both parent",
    "initialDiagnosis": "pre-hypertension",
    "physicalExam": "",
    "services": "Adult",
    "type": "Consult",
    "code": "Cardio",
    "category": null,
    "plan": "norvasc 500mg once a day, avoid stress",
    "pay": "personal",
    "referringDoctor": null,
    "labs": "",
    "imaging": "",
    "accident": "0",
    "painLevel": "1",
    "allergies": "none",
    "currentMedications": "",
    "date": "2016-03-29",
    "timeStart": "02:41:00",
    "timeEnd": null,
    "certRemarks": null,
    "certPurpose": null,
    "deleted_at": null,
    "created_at": "2016-03-29 02:45:14",
    "updated_at": "2016-03-29 02:45:14"
  },
  {
    "id": "5",
    "patientID": "3",
    "doctorID": "1",
    "appointmentID": null,
    "preparedByID": null,
    "chiefComplaint": "cough",
    "historyIllness": "The px comes to the clinic with complaints of coughing episodes for x days ",
    "bodyTemperature": "37",
    "bloodPressure": "120/80",
    "respirationRate": "17",
    "pulseRate": "75",
    "medicalHistory": "test",
    "initialDiagnosis": "upper resp tract infection",
    "physicalExam": "<p><br><\\/p><p>VS:<\\/p><p>HEENT:<\\/p><p>Neck:<\\/p><p>Lungs:<\\/p><p>CV:<\\/p><p>GI:<\\/p><p>GU:<\\/p><p>Pulses:<\\/p><p>Lymphs:<\\/p><p>Extremities:<\\/p><p>Neuro:<\\/p>",
    "services": "Adult",
    "type": "Consult",
    "code": "Pulmo-Resp",
    "category": null,
    "plan": "meds for x days",
    "pay": "company",
    "referringDoctor": null,
    "labs": "",
    "imaging": "",
    "accident": "0",
    "painLevel": "1",
    "allergies": "none",
    "currentMedications": "none",
    "date": "2016-04-04",
    "timeStart": "02:29:00",
    "timeEnd": null,
    "certRemarks": null,
    "certPurpose": null,
    "deleted_at": null,
    "created_at": "2016-04-04 02:32:22",
    "updated_at": "2016-04-04 02:32:22"
  },
  {
    "id": "6",
    "patientID": "7",
    "doctorID": "1",
    "appointmentID": null,
    "preparedByID": null,
    "chiefComplaint": "Diarrhea",
    "historyIllness": "loose bowel movement",
    "bodyTemperature": "36",
    "bloodPressure": "120/80",
    "respirationRate": "23",
    "pulseRate": "80",
    "medicalHistory": "",
    "initialDiagnosis": "ameobaiasis",
    "physicalExam": "",
    "services": "Adult",
    "type": "Consult",
    "code": "Medical",
    "category": null,
    "plan": "Take OMX 2x daily Morning\\/Evening\r\nDrink fluids",
    "pay": "personal",
    "referringDoctor": null,
    "labs": "",
    "imaging": "",
    "accident": "0",
    "painLevel": "2",
    "allergies": "none",
    "currentMedications": "None",
    "date": "2016-04-04",
    "timeStart": "09:00:00",
    "timeEnd": null,
    "certRemarks": null,
    "certPurpose": null,
    "deleted_at": null,
    "created_at": "2016-04-04 07:09:27",
    "updated_at": "2016-04-05 02:54:38"
  },
  {
    "id": "7",
    "patientID": "7",
    "doctorID": "1",
    "appointmentID": null,
    "preparedByID": null,
    "chiefComplaint": "elbow pain\r\n",
    "historyIllness": "basketball injury. fell on elbow. pain felt when rotating arm.",
    "bodyTemperature": "36",
    "bloodPressure": "110/80",
    "respirationRate": "22",
    "pulseRate": "88",
    "medicalHistory": "",
    "initialDiagnosis": "elbow sprain",
    "physicalExam": "",
    "services": "Sports Injury",
    "type": "X-Ray",
    "code": "Ortho",
    "category": null,
    "plan": "immobilization of affected area",
    "pay": "insurance",
    "referringDoctor": null,
    "labs": "",
    "imaging": "",
    "accident": "1",
    "painLevel": "3",
    "allergies": "n\\/a",
    "currentMedications": "n\\/a",
    "date": "2016-04-05",
    "timeStart": "12:30:00",
    "timeEnd": null,
    "certRemarks": null,
    "certPurpose": null,
    "deleted_at": null,
    "created_at": "2016-04-04 08:48:15",
    "updated_at": "2016-04-05 07:50:35"
  },
  {
    "id": "8",
    "patientID": "5",
    "doctorID": "1",
    "appointmentID": null,
    "preparedByID": null,
    "chiefComplaint": "test",
    "historyIllness": "Low Blood",
    "bodyTemperature": "36",
    "bloodPressure": "",
    "respirationRate": "",
    "pulseRate": "",
    "medicalHistory": "",
    "initialDiagnosis": "",
    "physicalExam": "<span style=font-weight: bold;>qwe<\\/span>",
    "services": "Adult",
    "type": "Consult",
    "code": "Medical",
    "category": null,
    "plan": "",
    "pay": "charity",
    "referringDoctor": null,
    "labs": "",
    "imaging": "",
    "accident": "0",
    "painLevel": "5",
    "allergies": "None",
    "currentMedications": "",
    "date": "2016-04-04",
    "timeStart": "08:26:00",
    "timeEnd": null,
    "certRemarks": null,
    "certPurpose": null,
    "deleted_at": "2016-04-04 09:39:01",
    "created_at": "2016-04-04 08:49:52",
    "updated_at": "2016-04-04 09:39:01"
  },
  {
    "id": "9",
    "patientID": "5",
    "doctorID": "2",
    "appointmentID": null,
    "preparedByID": null,
    "chiefComplaint": "Test",
    "historyIllness": "Test",
    "bodyTemperature": "ffsdfsfsd",
    "bloodPressure": "dsdsdfs",
    "respirationRate": "fdsfsfsfd",
    "pulseRate": "sfdsfdsfdsf",
    "medicalHistory": "weew",
    "initialDiagnosis": "",
    "physicalExam": "<p>fsdfsdfs<\\/p>",
    "services": "Sports Injury",
    "type": "Consult",
    "code": "Medical",
    "category": null,
    "plan": "",
    "pay": "charity",
    "referringDoctor": null,
    "labs": "",
    "imaging": "",
    "accident": "1",
    "painLevel": "7",
    "allergies": "",
    "currentMedications": "",
    "date": "2017-03-09",
    "timeStart": "21:40:00",
    "timeEnd": null,
    "certRemarks": null,
    "certPurpose": null,
    "deleted_at": "2016-04-04 09:38:55",
    "created_at": "2016-04-04 09:37:04",
    "updated_at": "2016-04-04 09:38:55"
  },
  {
    "id": "10",
    "patientID": "10",
    "doctorID": "1",
    "appointmentID": null,
    "preparedByID": null,
    "chiefComplaint": "demo",
    "historyIllness": "demo",
    "bodyTemperature": "12",
    "bloodPressure": "120\\/80",
    "respirationRate": "12",
    "pulseRate": "12",
    "medicalHistory": "demo",
    "initialDiagnosis": "",
    "physicalExam": "<p>asdffga<\\/p>",
    "services": "Adult",
    "type": "Consult",
    "code": "Medical",
    "category": null,
    "plan": "",
    "pay": "charity",
    "referringDoctor": null,
    "labs": "",
    "imaging": "",
    "accident": "0",
    "painLevel": "4",
    "allergies": "asdfasdf",
    "currentMedications": "asdfasdf",
    "date": "2016-05-03",
    "timeStart": "08:39:00",
    "timeEnd": null,
    "certRemarks": null,
    "certPurpose": null,
    "deleted_at": null,
    "created_at": "2016-05-03 08:41:14",
    "updated_at": "2016-05-03 08:41:14"
  },
  {
    "id": "11",
    "patientID": "11",
    "doctorID": "1",
    "appointmentID": null,
    "preparedByID": null,
    "chiefComplaint": "asdf",
    "historyIllness": "asdf",
    "bodyTemperature": "",
    "bloodPressure": "",
    "respirationRate": "",
    "pulseRate": "",
    "medicalHistory": "",
    "initialDiagnosis": "",
    "physicalExam": "<p>asdfasdf<\\/p>",
    "services": "Adult",
    "type": "Consult",
    "code": "Medical",
    "category": null,
    "plan": "",
    "pay": "charity",
    "referringDoctor": null,
    "labs": "",
    "imaging": "asdfassdf",
    "accident": "0",
    "painLevel": "1",
    "allergies": "",
    "currentMedications": "",
    "date": "2016-05-04",
    "timeStart": "01:49:00",
    "timeEnd": null,
    "certRemarks": null,
    "certPurpose": null,
    "deleted_at": null,
    "created_at": "2016-05-04 01:50:13",
    "updated_at": "2016-05-04 01:50:13"
  }
],
  "diagnosisIcds": [
    {
      "id": "5",
      "diagnosisID": "1",
      "icdID": "1987",
      "deleted_at": "NULL",
      "created_at": "2016-03-22 21:28:41",
      "updated_at": "2016-03-22 21:28:41"
    },
    {
      "id": "7",
      "diagnosisID": "2",
      "icdID": "1957",
      "deleted_at": "NULL",
      "created_at": "2016-03-28 01:49:08",
      "updated_at": "2016-03-28 01:49:08"
    },
    {
      "id": "13",
      "diagnosisID": "4",
      "icdID": "1952",
      "deleted_at": "NULL",
      "created_at": "2016-03-28 18:52:41",
      "updated_at": "2016-03-28 18:52:41"
    },
    {
      "id": "20",
      "diagnosisID": "3",
      "icdID": "1950",
      "deleted_at": "NULL",
      "created_at": "2016-03-28 21:43:35",
      "updated_at": "2016-03-28 21:43:35"
    },
    {
      "id": "23",
      "diagnosisID": "5",
      "icdID": "1946",
      "deleted_at": "NULL",
      "created_at": "2016-04-03 18:34:11",
      "updated_at": "2016-04-03 18:34:11"
    },
    {
      "id": "27",
      "diagnosisID": "9",
      "icdID": "1949",
      "deleted_at": "2016-04-04 01:38:55",
      "created_at": "2016-04-04 01:37:04",
      "updated_at": "2016-04-04 01:38:55"
    },
    {
      "id": "28",
      "diagnosisID": "9",
      "icdID": "1950",
      "deleted_at": "2016-04-04 01:38:55",
      "created_at": "2016-04-04 01:37:04",
      "updated_at": "2016-04-04 01:38:55"
    },
    {
      "id": "29",
      "diagnosisID": "9",
      "icdID": "1948",
      "deleted_at": "2016-04-04 01:38:55",
      "created_at": "2016-04-04 01:37:04",
      "updated_at": "2016-04-04 01:38:55"
    },
    {
      "id": "30",
      "diagnosisID": "9",
      "icdID": "1946",
      "deleted_at": "2016-04-04 01:38:55",
      "created_at": "2016-04-04 01:37:04",
      "updated_at": "2016-04-04 01:38:55"
    },
    {
      "id": "33",
      "diagnosisID": "6",
      "icdID": "1987",
      "deleted_at": "NULL",
      "created_at": "2016-04-04 18:54:38",
      "updated_at": "2016-04-04 18:54:38"
    }
  ],
  "discharging": [
    {
      "id": "3",
      "postDiagnosisID": "6",
      "admittingID": "1",
      "complications": "NULL",
      "finalDiagnosis": "",
      "date": "2016-03-29",
      "deleted_at": "NULL",
      "created_at": "2016-03-28 22:55:22",
      "updated_at": "2016-03-28 22:55:22"
    },
    {
      "id": "4",
      "postDiagnosisID": "7",
      "admittingID": "2",
      "complications": "NULL",
      "finalDiagnosis": "cut",
      "date": "2016-04-04",
      "deleted_at": "NULL",
      "created_at": "2016-04-03 18:40:20",
      "updated_at": "2016-04-03 18:40:20"
    },
    {
      "id": "5",
      "postDiagnosisID": "8",
      "admittingID": "5",
      "complications": "NULL",
      "finalDiagnosis": "",
      "date": "2016-04-05",
      "deleted_at": "NULL",
      "created_at": "2016-04-04 22:44:59",
      "updated_at": "2016-04-04 22:44:59"
    },
    {
      "id": "6",
      "postDiagnosisID": "9",
      "admittingID": "8",
      "complications": "NULL",
      "finalDiagnosis": "",
      "date": "2016-04-05",
      "deleted_at": "NULL",
      "created_at": "2016-04-04 23:44:51",
      "updated_at": "2016-04-04 23:44:51"
    },
    {
      "id": "7",
      "postDiagnosisID": "10",
      "admittingID": "9",
      "complications": "NULL",
      "finalDiagnosis": "",
      "date": "2016-05-03",
      "deleted_at": "NULL",
      "created_at": "2016-05-03 00:55:15",
      "updated_at": "2016-05-03 00:55:15"
    }
  ],
  "doctors": [
    {
      "id": "1",
      "groupID": "1",
      "patientID": "0",
      "userID": "26",
      "firstname": "Benedicto",
      "middlename": "Serrosa",
      "lastname": "Tan Gan",
      "nameSuffix": "",
      "birthdate": "1970-03-28",
      "sex": "1",
      "status": "Married",
      "address": "Unit 12 Raffles Building",
      "initial": "Ortigas Pasig",
      "type": "BTG",
      "code": "Gastrointestinal",
      "phone1": "0",
      "phone2": "091147744441",
      "rank": "28144441",
      "email": "Fellow",
      "licenseID": "btangan@gmail.com",
      "imagePath": "444144",
      "imageMime": "avatar/70fb6af8-9949-4b90-bf38-0a2583275105.jpg",
      "allowAsPatient": "jpg",
      "schedule": "NULL",
      "deleted_at": "NULL",
      "created_at": "NULL",
      "updated_at": "2016-03-22 21:12:36"
    },
    {
      "id": "2",
      "groupID": "1",
      "patientID": "6",
      "userID": "28",
      "firstname": "Roger",
      "middlename": "Alonzo",
      "lastname": "Javellana",
      "nameSuffix": "",
      "birthdate": "1975-03-12",
      "sex": "1",
      "status": "Married",
      "address": "#45 Summer Breeze Subdivision Pasig City",
      "initial": "RAJ",
      "type": "Orthopedics",
      "code": "0",
      "phone1": "094512124411",
      "phone2": "7841111",
      "rank": "Fellow",
      "email": "javelan@gmail.com",
      "licenseID": "14245",
      "imagePath": "avatar/1febc863-f96f-4e3d-b6ab-701e359c9604.jpg",
      "imageMime": "jpg",
      "allowAsPatient": "1",
      "schedule": "NULL",
      "deleted_at": "NULL",
      "created_at": "2016-03-28 16:47:04",
      "updated_at": "2016-03-28 16:54:57"
    },
    {
      "id": "3",
      "groupID": "1",
      "patientID": "NULL",
      "userID": "29",
      "firstname": "Vergel",
      "middlename": "Ocampo",
      "lastname": "De Dios",
      "nameSuffix": "",
      "birthdate": "1962-03-01",
      "sex": "1",
      "status": "Married",
      "address": "#4 Sikatuna Subdivision Quezon City",
      "initial": "VDD",
      "type": "Pulmonologist",
      "code": "0",
      "phone1": "09154421444",
      "phone2": "7451211",
      "rank": "Consultant",
      "email": "VDD1@yahoo.com",
      "licenseID": "41211",
      "imagePath": "NULL",
      "imageMime": "jpg",
      "allowAsPatient": "NULL",
      "schedule": "NULL",
      "deleted_at": "NULL",
      "created_at": "2016-03-28 16:52:20",
      "updated_at": "2016-08-15 23:30:53"
    },
    {
      "id": "4",
      "groupID": "1",
      "patientID": "12",
      "userID": "NULL",
      "firstname": "Joel",
      "middlename": "",
      "lastname": "Garcia",
      "nameSuffix": "MD",
      "birthdate": "1983-04-19",
      "sex": "1",
      "status": "Single",
      "address": "",
      "initial": "JGG",
      "type": "",
      "code": "0",
      "phone1": "09178888888",
      "phone2": "",
      "rank": "",
      "email": "joel@gmail.com",
      "licenseID": "1234121323",
      "imagePath": "NULL",
      "imageMime": "jpg",
      "allowAsPatient": "1",
      "schedule": "NULL",
      "deleted_at": "NULL",
      "created_at": "2016-05-03 18:09:12",
      "updated_at": "2016-05-03 18:09:12"
    }
  ],
  "followup": [
    {
      "id": "2",
      "diagnosisID": "2",
      "date": "2016-03-31",
      "time": "09:45:00",
      "findings": "NULL",
      "implants": "NULL",
      "antibiotics": "NULL",
      "transfusion": "NULL",
      "description": "<p><br></p>",
      "name": "gastroenteritis bacterial in origin",
      "emergencyOrElective": "elective",
      "pay": "hmo",
      "leadSurgeon": "1",
      "otherDoctors": "NULL",
      "labs": "",
      "xrays": "",
      "deleted_at": "NULL",
      "created_at": "2016-03-28 01:49:08",
      "updated_at": "2016-03-28 01:49:08"
    },
    {
      "id": "3",
      "diagnosisID": "3",
      "date": "2016-03-31",
      "time": "13:45:00",
      "findings": "NULL",
      "implants": "NULL",
      "antibiotics": "NULL",
      "transfusion": "NULL",
      "description": "<p><br></p>",
      "name": "bronchial asthma",
      "emergencyOrElective": "elective",
      "pay": "insurance",
      "leadSurgeon": "3",
      "otherDoctors": "NULL",
      "labs": "",
      "xrays": "",
      "deleted_at": "NULL",
      "created_at": "2016-03-28 17:39:51",
      "updated_at": "2016-03-28 17:39:51"
    },
    {
      "id": "4",
      "diagnosisID": "4",
      "date": "2016-03-29",
      "time": "02:45:00",
      "findings": "NULL",
      "implants": "NULL",
      "antibiotics": "NULL",
      "transfusion": "NULL",
      "description": "<p><br></p>",
      "name": "hypertension",
      "emergencyOrElective": "elective",
      "pay": "personal",
      "leadSurgeon": "2",
      "otherDoctors": "NULL",
      "labs": "",
      "xrays": "",
      "deleted_at": "NULL",
      "created_at": "2016-03-28 18:50:37",
      "updated_at": "2016-03-28 18:51:00"
    },
    {
      "id": "5",
      "diagnosisID": "5",
      "date": "2016-04-11",
      "time": "02:30:00",
      "findings": "NULL",
      "implants": "NULL",
      "antibiotics": "NULL",
      "transfusion": "NULL",
      "description": "test",
      "name": "test",
      "emergencyOrElective": "elective",
      "pay": "company",
      "leadSurgeon": "1",
      "otherDoctors": "NULL",
      "labs": "",
      "xrays": "",
      "deleted_at": "NULL",
      "created_at": "2016-04-03 18:33:59",
      "updated_at": "2016-04-03 18:34:11"
    },
    {
      "id": "6",
      "diagnosisID": "7",
      "date": "2016-04-07",
      "time": "09:30:00",
      "findings": "NULL",
      "implants": "NULL",
      "antibiotics": "NULL",
      "transfusion": "NULL",
      "description": "<p>check for recovery process and further rehabilitation methods if necessary</p>",
      "name": "elbow sprain",
      "emergencyOrElective": "elective",
      "pay": "personal",
      "leadSurgeon": "1",
      "otherDoctors": "NULL",
      "labs": "",
      "xrays": "",
      "deleted_at": "NULL",
      "created_at": "2016-04-06 17:25:02",
      "updated_at": "2016-04-06 17:25:02"
    },
    {
      "id": "7",
      "diagnosisID": "10",
      "date": "2016-05-03",
      "time": "08:45:00",
      "findings": "NULL",
      "implants": "NULL",
      "antibiotics": "NULL",
      "transfusion": "NULL",
      "description": "<p>demo</p>",
      "name": "demo",
      "emergencyOrElective": "elective",
      "pay": "charity",
      "leadSurgeon": "1",
      "otherDoctors": "NULL",
      "labs": "",
      "xrays": "",
      "deleted_at": "NULL",
      "created_at": "2016-05-03 00:42:47",
      "updated_at": "2016-05-03 00:42:47"
    },
    {
      "id": "8",
      "diagnosisID": "11",
      "date": "2016-05-04",
      "time": "14:45:00",
      "findings": "NULL",
      "implants": "NULL",
      "antibiotics": "NULL",
      "transfusion": "NULL",
      "description": "<p>asdfasdf</p>",
      "name": "asdfasdf",
      "emergencyOrElective": "elective",
      "pay": "charity",
      "leadSurgeon": "1",
      "otherDoctors": "NULL",
      "labs": "asdf",
      "xrays": "asdf",
      "deleted_at": "NULL",
      "created_at": "2016-05-03 17:50:37",
      "updated_at": "2016-05-03 17:53:22"
    }
  ],
  "followupIcds": [],
  "genericMedicine": [
  {
    "id": "1",
    "name": "Paracetamol",
    "deleted_at": null,
    "created_at": "2016-10-06 07:17:11",
    "updated_at": "2016-10-06 07:17:11"
  }
],
  "groupMembers": [],
  "groups": [
    {
      "id": "1",
      "name": "ConciergeMed",
      "address": "Discovery Primea",
      "owner": "Joel Garcia",
      "licenseNum": "",
      "status": "1",
      "established": "2014",
      "deleted_at": "NULL",
      "created_at": "2016-03-22 21:05:04",
      "updated_at": "2016-03-22 21:05:04",
      "logo": "NULL);"
    }
  ],
  "hospitalAffiliatedFacility": [],
  "hospitals": [],
  "icdCategories": [],
  "labItemClass": [
    {
      "id": "1",
      "value": "Blood Chemistry",
      "deleted_at": "NULL",
      "created_at": "0000-00-00 00:00:00",
      "updated_at": "0000-00-00 00:00:00"
    },
    {
      "id": "2",
      "value": "Cardiovascular",
      "deleted_at": "NULL",
      "created_at": "0000-00-00 00:00:00",
      "updated_at": "0000-00-00 00:00:00"
    },
    {
      "id": "3",
      "value": "Culture",
      "deleted_at": "NULL",
      "created_at": "0000-00-00 00:00:00",
      "updated_at": "0000-00-00 00:00:00"
    },
    {
      "id": "4",
      "value": "Special Exams",
      "deleted_at": "NULL",
      "created_at": "0000-00-00 00:00:00",
      "updated_at": "0000-00-00 00:00:00"
    },
    {
      "id": "5",
      "value": "Standard Labs",
      "deleted_at": "NULL",
      "created_at": "0000-00-00 00:00:00",
      "updated_at": "0000-00-00 00:00:00"
    },
    {
      "id": "6",
      "value": "Ultrasonogram",
      "deleted_at": "NULL",
      "created_at": "0000-00-00 00:00:00",
      "updated_at": "0000-00-00 00:00:00"
    },
    {
      "id": "7",
      "value": "X-ray Examinations",
      "deleted_at": "NULL",
      "created_at": "0000-00-00 00:00:00",
      "updated_at": "0000-00-00 00:00:00"
    },
    {
      "id": "8",
      "value": "Unclassified Lab Item",
      "deleted_at": "NULL",
      "created_at": "0000-00-00 00:00:00",
      "updated_at": "0000-00-00 00:00:00"
    }
  ],
  "labwork": [
    {
      "id": "1",
      "patientID": "3",
      "userID": "0",
      "orderDate": "2016-03-28",
      "completionDate": "NULL",
      "completed": "NULL",
      "labData": "46@@108@@110:::@@@@",
      "viewed": "NULL",
      "deleted_at": "NULL",
      "created_at": "2016-03-28 01:45:15",
      "updated_at": "2016-03-28 01:45:15"
    },
    {
      "id": "2",
      "patientID": "3",
      "userID": "0",
      "orderDate": "2016-03-28",
      "completionDate": "NULL",
      "completed": "NULL",
      "labData": "110:::",
      "viewed": "NULL",
      "deleted_at": "NULL",
      "created_at": "2016-03-28 01:45:25",
      "updated_at": "2016-03-28 01:45:25"
    },
    {
      "id": "3",
      "patientID": "5",
      "userID": "0",
      "orderDate": "2016-03-29",
      "completionDate": "NULL",
      "completed": "NULL",
      "labData": "65@@110:::@@",
      "viewed": "NULL",
      "deleted_at": "NULL",
      "created_at": "2016-03-28 18:35:46",
      "updated_at": "2016-03-28 18:35:46"
    },
    {
      "id": "4",
      "patientID": "5",
      "userID": "0",
      "orderDate": "2016-03-29",
      "completionDate": "NULL",
      "completed": "NULL",
      "labData": "1@@4:::@@",
      "viewed": "NULL",
      "deleted_at": "NULL",
      "created_at": "2016-03-28 19:14:21",
      "updated_at": "2016-03-28 19:14:21"
    },
    {
      "id": "5",
      "patientID": "3",
      "userID": "0",
      "orderDate": "2016-04-04",
      "completionDate": "2016-04-04",
      "completed": "1",
      "labData": "1@@38:::12@@12",
      "viewed": "NULL",
      "deleted_at": "NULL",
      "created_at": "2016-04-03 18:35:29",
      "updated_at": "2016-04-04 02:01:26"
    },
    {
      "id": "6",
      "patientID": "7",
      "userID": "0",
      "orderDate": "2016-04-04",
      "completionDate": "NULL",
      "completed": "1",
      "labData": "109:::",
      "viewed": "NULL",
      "deleted_at": "NULL",
      "created_at": "2016-04-03 23:07:47",
      "updated_at": "2016-04-04 02:01:37"
    },
    {
      "id": "7",
      "patientID": "7",
      "userID": "0",
      "orderDate": "2016-04-04",
      "completionDate": "2016-04-07",
      "completed": "1",
      "labData": "109:::normal",
      "viewed": "NULL",
      "deleted_at": "NULL",
      "created_at": "2016-04-03 23:08:07",
      "updated_at": "2016-04-06 18:02:29"
    },
    {
      "id": "8",
      "patientID": "10",
      "userID": "0",
      "orderDate": "2016-05-03",
      "completionDate": "2016-05-03",
      "completed": "1",
      "labData": "4@@26@@40@@44@@46@@48@@56@@110:::ok@@ok@@ok@@Ok@@ok@@ok@@OK@@oK",
      "viewed": "NULL",
      "deleted_at": "NULL",
      "created_at": "2016-05-03 00:40:59",
      "updated_at": "2016-05-03 00:50:23"
    }
  ],
  "medicineDosages": [
  {
    "id": "5",
    "medicineID": "1",
    "dosage": "10mL",
    "frequency": "",
    "form": "Tablets",
    "deleted_at": null,
    "created_at": "2016-10-10 01:46:03",
    "updated_at": "2016-10-10 01:46:03"
  },
  {
    "id": "6",
    "medicineID": "1",
    "dosage": "20mL",
    "frequency": "",
    "form": "Tablets",
    "deleted_at": null,
    "created_at": "2016-10-10 01:46:03",
    "updated_at": "2016-10-10 01:46:03"
  },
  {
    "id": "7",
    "medicineID": "1",
    "dosage": "30mL",
    "frequency": "",
    "form": "Tablets",
    "deleted_at": null,
    "created_at": "2016-10-10 01:46:03",
    "updated_at": "2016-10-10 01:46:03"
  },
  {
    "id": "11",
    "medicineID": "2",
    "dosage": "10mg",
    "frequency": "Three times a day ",
    "form": "Tablets",
    "deleted_at": null,
    "created_at": "2016-10-10 01:47:31",
    "updated_at": "2016-10-10 01:47:31"
  },
  {
    "id": "12",
    "medicineID": "2",
    "dosage": "400mg",
    "frequency": "Twice a day ",
    "form": "Tablets",
    "deleted_at": null,
    "created_at": "2016-10-10 01:47:31",
    "updated_at": "2016-10-10 01:47:31"
  }
],
  "medicines": [
  {
    "id": "1",
    "genericMedicineID": "1",
    "groupID": null,
    "properName": "Biogesic",
    "manufacturer": "Biogesic",
    "deleted_at": null,
    "created_at": "2016-10-06 07:17:39",
    "updated_at": "2016-10-06 07:17:39"
  },
  {
    "id": "2",
    "genericMedicineID": "1",
    "groupID": null,
    "properName": "Alaxan",
    "manufacturer": "Alaxan",
    "deleted_at": null,
    "created_at": "2016-10-10 01:46:58",
    "updated_at": "2016-10-10 01:46:58"
  }
],
  "migrations": [
    {
      "migration": "2014_10_12_000000_create_users_table",
      "batch": "1);"
    },
    {
      "migration": "2014_10_12_100000_create_password_resets_table",
      "batch": "1);"
    },
    {
      "migration": "2015_09_17_023219_create_patients_table",
      "batch": "1);"
    },
    {
      "migration": "2015_09_17_054433_create_doctors_table",
      "batch": "1);"
    },
    {
      "migration": "2015_09_17_073301_create_diagnosis_table",
      "batch": "1);"
    },
    {
      "migration": "2015_09_18_034351_create_user_access_level_table",
      "batch": "1);"
    },
    {
      "migration": "2015_09_21_060355_create_prescriptions_table",
      "batch": "1);"
    },
    {
      "migration": "2015_09_21_060414_create_appointments_table",
      "batch": "1);"
    },
    {
      "migration": "2015_09_24_084359_create_followup_table",
      "batch": "1);"
    },
    {
      "migration": "2015_09_24_085212_create_diagnosis_icds_table",
      "batch": "1);"
    },
    {
      "migration": "2015_09_24_085236_create_icds_table",
      "batch": "1);"
    },
    {
      "migration": "2015_09_24_085314_create_icd_categories_table",
      "batch": "1);"
    },
    {
      "migration": "2015_09_24_090056_create_procedures_table",
      "batch": "1);"
    },
    {
      "migration": "2015_09_24_090206_create_procedure_cpts_table",
      "batch": "1);"
    },
    {
      "migration": "2015_09_24_090234_create_procedure_doctors_table",
      "batch": "1);"
    },
    {
      "migration": "2015_09_28_022312_create_patient_images_table",
      "batch": "1);"
    },
    {
      "migration": "2015_09_28_033419_create_admitting_table",
      "batch": "1);"
    },
    {
      "migration": "2015_09_28_054902_create_pe_templates_table",
      "batch": "1);"
    },
    {
      "migration": "2015_09_28_054948_create_procedure_templates_table",
      "batch": "1);"
    },
    {
      "migration": "2015_09_28_060342_create_pe_categories_table",
      "batch": "1);"
    },
    {
      "migration": "2015_09_28_060415_create_procedure_categories_table",
      "batch": "1);"
    },
    {
      "migration": "2015_09_29_033051_create_discharging_table",
      "batch": "1);"
    },
    {
      "migration": "2015_09_29_033135_create_post_diagnosis_table",
      "batch": "1);"
    },
    {
      "migration": "2015_09_29_052613_create_cpts_table",
      "batch": "1);"
    },
    {
      "migration": "2015_09_29_052946_create_followup_icds_table",
      "batch": "1);"
    },
    {
      "migration": "2015_09_29_053204_create_cpt_categories_table",
      "batch": "1);"
    },
    {
      "migration": "2015_10_01_031102_create_labwork_table",
      "batch": "1);"
    },
    {
      "migration": "2015_10_01_031138_create_lab_item_table",
      "batch": "1);"
    },
    {
      "migration": "2015_10_01_032111_create_lab_item_class_table",
      "batch": "1);"
    },
    {
      "migration": "2015_10_01_063756_create_hospitals_table",
      "batch": "1);"
    },
    {
      "migration": "2015_10_01_064553_create_hospital_affiliated_facility_table",
      "batch": "1);"
    },
    {
      "migration": "2015_10_07_014545_create_table_logger_table",
      "batch": "1);"
    },
    {
      "migration": "2015_10_13_074157_create_medicines_table",
      "batch": "1);"
    },
    {
      "migration": "2015_10_13_074251_create_medicine_dosages_table",
      "batch": "1);"
    },
    {
      "migration": "2015_10_13_080041_create_generic_medicine_table",
      "batch": "1);"
    },
    {
      "migration": "2015_10_13_080155_create_vaccines_table",
      "batch": "1);"
    },
    {
      "migration": "2015_10_13_080226_create_vaccine_records_table",
      "batch": "1);"
    },
    {
      "migration": "2015_10_14_054536_create_group_members_table",
      "batch": "1);"
    },
    {
      "migration": "2015_10_14_054737_create_groups_table",
      "batch": "1);"
    },
    {
      "migration": "2015_10_15_015403_create_staff_table",
      "batch": "1);"
    },
    {
      "migration": "2015_10_15_015430_create_nurses_table",
      "batch": "1);"
    },
    {
      "migration": "2015_11_12_043046_create_cache_table",
      "batch": "1);"
    },
    {
      "migration": "2016_01_11_055354_create_bmi_records_table",
      "batch": "1);"
    }
  ],
  "nurses": [
    {
      "id": "1",
      "groupID": "1",
      "patientID": "NULL",
      "userID": "23",
      "firstname": "Nurse1",
      "middlename": "",
      "lastname": "Nurse1",
      "nameSuffix": "",
      "birthdate": "2016-03-28",
      "sex": "1",
      "status": "Single",
      "address": "",
      "type": "NULL",
      "phone1": "1231412431",
      "phone2": "",
      "position": "",
      "email": "nurse@nurse.com",
      "licenseID": "",
      "imagePath": "NULL",
      "imageMime": "jpg",
      "allowAsPatient": "0",
      "schedule": "0",
      "deleted_at": "NULL",
      "created_at": "2016-03-27 18:06:36",
      "updated_at": "2016-03-27 18:07:48"
    },
    {
      "id": "2",
      "groupID": "1",
      "patientID": "NULL",
      "userID": "NULL",
      "firstname": "Geraldine",
      "middlename": "Yanez",
      "lastname": "Velez",
      "nameSuffix": "",
      "birthdate": "1974-02-06",
      "sex": "0",
      "status": "Married",
      "address": "87 Abad Santos St. Dagupan Metro Manila",
      "type": "NULL",
      "phone1": "0941411000",
      "phone2": "8942475",
      "position": "Sr. Nurse",
      "email": "velez_ge2123@yahoo.com",
      "licenseID": "142567",
      "imagePath": "NULL",
      "imageMime": "jpg",
      "allowAsPatient": "1",
      "schedule": "0",
      "deleted_at": "NULL",
      "created_at": "2016-03-28 01:36:54",
      "updated_at": "2016-03-28 01:36:54"
    }
  ],
  "password_resets": [],
  "patientImages": [
    {
      "id": "1",
      "patientID": "5",
      "assocRecordID": "3",
      "image": "32848b76-b9e8-4b0a-89fb-e846bb5812b7.jpg",
      "image1": "NULL",
      "imageAnnotation": "taken at San Carlos Medical & Diagnostic Clinic",
      "forDisplay": "NULL",
      "imageType": "jpg",
      "imageModule": "diagnosis",
      "deleted_at": "NULL",
      "created_at": "2016-03-28 17:11:10",
      "updated_at": "2016-03-28 17:13:15"
    },
    {
      "id": "2",
      "patientID": "4",
      "assocRecordID": "4",
      "image": "dd4b034a-0f23-4f11-b92d-4414d4a07c33.jpg",
      "image1": "NULL",
      "imageAnnotation": "",
      "forDisplay": "NULL",
      "imageType": "jpg",
      "imageModule": "follow-up",
      "deleted_at": "NULL",
      "created_at": "2016-03-28 18:48:01",
      "updated_at": "2016-03-28 18:50:37"
    },
    {
      "id": "3",
      "patientID": "4",
      "assocRecordID": "4",
      "image": "9a0140c6-80d9-415f-b722-e4e811469824.jpg",
      "image1": "NULL",
      "imageAnnotation": "taken 022016",
      "forDisplay": "NULL",
      "imageType": "jpg",
      "imageModule": "diagnosis",
      "deleted_at": "NULL",
      "created_at": "2016-03-28 18:52:35",
      "updated_at": "2016-03-28 18:52:35"
    },
    {
      "id": "4",
      "patientID": "5",
      "assocRecordID": "3",
      "image": "016d03ad-c247-47c8-a0e2-ed1eac365360.jpg",
      "image1": "NULL",
      "imageAnnotation": "Test",
      "forDisplay": "NULL",
      "imageType": "jpg",
      "imageModule": "diagnosis",
      "deleted_at": "NULL",
      "created_at": "2016-03-28 22:39:15",
      "updated_at": "2016-03-28 22:39:15"
    },
    {
      "id": "5",
      "patientID": "7",
      "assocRecordID": "7",
      "image": "e885dbb6-809a-45f7-bc3e-529cabeb8aa9.jpg",
      "image1": "NULL",
      "imageAnnotation": "",
      "forDisplay": "NULL",
      "imageType": "jpg",
      "imageModule": "diagnosis",
      "deleted_at": "NULL",
      "created_at": "2016-04-04 17:35:07",
      "updated_at": "2016-04-04 17:35:07"
    },
    {
      "id": "6",
      "patientID": "10",
      "assocRecordID": "NULL",
      "image": "b9852a7a-14ec-4cea-b327-2216b584ee95.jpg",
      "image1": "NULL",
      "imageAnnotation": "",
      "forDisplay": "NULL",
      "imageType": "jpg",
      "imageModule": "NULL",
      "deleted_at": "2016-05-03 00:59:37",
      "created_at": "2016-05-03 00:58:36",
      "updated_at": "2016-05-03 00:59:37"
    }
  ],
  "patients": [
    {
      "id": "2",
      "otherID": "NULL",
      "groupID": "1",
      "userID": "NULL",
      "primaryDoc": "0",
      "secondaryDoc": "0",
      "referredByID": "NULL",
      "code": "2",
      "category": "Resident",
      "firstname": "Juan",
      "lastname": "Salcedo",
      "middlename": "Diaz",
      "nickname": "NULL",
      "birthdate": "1975-01-06",
      "birthPlace": "NULL",
      "religion": "",
      "address": "#18 San Isidro St. Makati City",
      "status": "Married",
      "occupation": "businessman",
      "sex": "1",
      "race": "NULL",
      "nationality": "NULL",
      "height": "",
      "hmoID": "12132",
      "hmo": "Philcare",
      "hmoCode": "112332",
      "telHome": "028457577",
      "telOffice": "NULL",
      "telMobile": "0914758877",
      "email": "salcedo12@gmail.com",
      "company": "Red Lane IT Group",
      "companyAddress": "Cityland Makati City",
      "companyContact": "NULL",
      "companyID": "0010",
      "personNotify": "Grace Salcedo",
      "personMobile": "",
      "personRelation": "NULL",
      "personAddress": "NULL",
      "insuranceProvider": "",
      "accountVerified": "0",
      "policyNumber": "",
      "imagePath": "avatar/b251463b-5402-428d-afd2-91d4ac188192.jpg",
      "imageMime": "jpg",
      "isPedia": "0",
      "fatherName": "NULL",
      "motherName": "NULL",
      "guardianName": "NULL",
      "spouseName": "NULL",
      "deleted_at": "NULL",
      "created_at": "2016-03-22 20:32:47",
      "updated_at": "2016-03-22 20:35:08"
    },
    {
      "id": "3",
      "otherID": "NULL",
      "groupID": "1",
      "userID": "NULL",
      "primaryDoc": "0",
      "secondaryDoc": "0",
      "referredByID": "NULL",
      "code": "3",
      "category": "Resident",
      "firstname": "Rafael",
      "lastname": "Gomez",
      "middlename": "Diaz",
      "nickname": "Raf",
      "birthdate": "1970-09-16",
      "birthPlace": "Manila",
      "religion": "Catholic",
      "address": "20 Congressional Road Quezon City",
      "status": "Single",
      "occupation": "Construction",
      "sex": "1",
      "race": "Filipino",
      "nationality": "Filipino",
      "height": "",
      "hmoID": "01144",
      "hmo": "Philcare",
      "hmoCode": "Philcare1234234",
      "telHome": "",
      "telOffice": "NULL",
      "telMobile": "09441111111",
      "email": "rafgomez2@gmail.com",
      "company": "Gomez & Sons Construction",
      "companyAddress": "Congressional Avenue QC",
      "companyContact": "",
      "companyID": "04",
      "personNotify": "Gina Gomez",
      "personMobile": "09163296956",
      "personRelation": "",
      "personAddress": "",
      "insuranceProvider": "Sun Life",
      "accountVerified": "0",
      "policyNumber": "SL134342",
      "imagePath": "avatar/7e2265c9-8134-4365-bb10-b34e59dbaf95.jpg",
      "imageMime": "jpg",
      "isPedia": "NULL",
      "fatherName": "",
      "motherName": "",
      "guardianName": "",
      "spouseName": "",
      "deleted_at": "NULL",
      "created_at": "2016-03-22 21:25:48",
      "updated_at": "2016-08-16 18:16:42"
    },
    {
      "id": "4",
      "otherID": "NULL",
      "groupID": "1",
      "userID": "NULL",
      "primaryDoc": "0",
      "secondaryDoc": "0",
      "referredByID": "NULL",
      "code": "4",
      "category": "Resident",
      "firstname": "Jeremy",
      "lastname": "Sandoval",
      "middlename": "Falcon",
      "nickname": "",
      "birthdate": "1972-01-17",
      "birthPlace": "",
      "religion": "Catholic",
      "address": "",
      "status": "Married",
      "occupation": "businessman",
      "sex": "0",
      "race": "",
      "nationality": "",
      "height": "",
      "hmoID": "",
      "hmo": "",
      "hmoCode": "",
      "telHome": "",
      "telOffice": "NULL",
      "telMobile": "091467711144",
      "email": "",
      "company": "",
      "companyAddress": "",
      "companyContact": "",
      "companyID": "",
      "personNotify": "",
      "personMobile": "",
      "personRelation": "",
      "personAddress": "",
      "insuranceProvider": "",
      "accountVerified": "0",
      "policyNumber": "",
      "imagePath": "NULL",
      "imageMime": "jpg",
      "isPedia": "NULL",
      "fatherName": "",
      "motherName": "",
      "guardianName": "",
      "spouseName": "",
      "deleted_at": "NULL",
      "created_at": "2016-03-23 18:17:56",
      "updated_at": "2016-03-28 22:20:30"
    },
    {
      "id": "5",
      "otherID": "NULL",
      "groupID": "1",
      "userID": "NULL",
      "primaryDoc": "0",
      "secondaryDoc": "0",
      "referredByID": "NULL",
      "code": "5",
      "category": "Resident",
      "firstname": "Harold",
      "lastname": "Abad",
      "middlename": "Roque",
      "nickname": "Rold",
      "birthdate": "1959-05-01",
      "birthPlace": "Antipolo Rizal",
      "religion": "Seventh Day Adventist",
      "address": "Pasong Tamo",
      "status": "Widowed",
      "occupation": "businessman",
      "sex": "1",
      "race": "",
      "nationality": "",
      "height": "",
      "hmoID": "ID091145",
      "hmo": "1111",
      "hmoCode": "1114",
      "telHome": "",
      "telOffice": "NULL",
      "telMobile": "0914711144",
      "email": "",
      "company": "",
      "companyAddress": "",
      "companyContact": "",
      "companyID": "",
      "personNotify": "",
      "personMobile": "",
      "personRelation": "",
      "personAddress": "",
      "insuranceProvider": "",
      "accountVerified": "0",
      "policyNumber": "",
      "imagePath": "avatar/de28b741-6a4d-40a5-9f17-3bb6d34e755b.jpg",
      "imageMime": "jpg",
      "isPedia": "NULL",
      "fatherName": "",
      "motherName": "",
      "guardianName": "",
      "spouseName": "",
      "deleted_at": "NULL",
      "created_at": "2016-03-23 19:15:54",
      "updated_at": "2016-03-28 22:40:30"
    },
    {
      "id": "7",
      "otherID": "NULL",
      "groupID": "1",
      "userID": "NULL",
      "primaryDoc": "2",
      "secondaryDoc": "1",
      "referredByID": "NULL",
      "code": "7",
      "category": "Employee",
      "firstname": "Juan",
      "lastname": "dela Cruz",
      "middlename": "Perez",
      "nickname": "Juan",
      "birthdate": "1998-07-01",
      "birthPlace": "Manila",
      "religion": "Roman Catholic",
      "address": "31 Sulu St Brgy San Lorenzo",
      "status": "Single",
      "occupation": "businessman",
      "sex": "1",
      "race": "",
      "nationality": "",
      "height": "",
      "hmoID": "",
      "hmo": "",
      "hmoCode": "",
      "telHome": "",
      "telOffice": "NULL",
      "telMobile": "09175555555",
      "email": "",
      "company": "",
      "companyAddress": "",
      "companyContact": "",
      "companyID": "",
      "personNotify": "",
      "personMobile": "",
      "personRelation": "",
      "personAddress": "",
      "insuranceProvider": "",
      "accountVerified": "0",
      "policyNumber": "",
      "imagePath": "NULL",
      "imageMime": "jpg",
      "isPedia": "NULL",
      "fatherName": "",
      "motherName": "",
      "guardianName": "",
      "spouseName": "",
      "deleted_at": "NULL",
      "created_at": "2016-04-03 22:59:18",
      "updated_at": "2016-08-16 18:20:00"
    },
    {
      "id": "8",
      "otherID": "NULL",
      "groupID": "1",
      "userID": "NULL",
      "primaryDoc": "0",
      "secondaryDoc": "0",
      "referredByID": "NULL",
      "code": "8",
      "category": "Resident",
      "firstname": "Ambrosio",
      "lastname": "Santos",
      "middlename": "Jose Nilo",
      "nickname": "Nilo",
      "birthdate": "1942-09-18",
      "birthPlace": "Manila",
      "religion": "Roman Catholic",
      "address": "34 M Rodriguez St Philamlife Village Pamplona Dos Las Pinas City",
      "status": "Married",
      "occupation": "businessman",
      "sex": "1",
      "race": "Brown",
      "nationality": "Filipino",
      "height": "NULL",
      "hmoID": "",
      "hmo": "",
      "hmoCode": "",
      "telHome": "(632) 8732273",
      "telOffice": "NULL",
      "telMobile": "09174180510",
      "email": "",
      "company": "",
      "companyAddress": "",
      "companyContact": "NULL",
      "companyID": "",
      "personNotify": "",
      "personMobile": "",
      "personRelation": "",
      "personAddress": "",
      "insuranceProvider": "",
      "accountVerified": "0",
      "policyNumber": "",
      "imagePath": "NULL",
      "imageMime": "jpg",
      "isPedia": "NULL",
      "fatherName": "",
      "motherName": "",
      "guardianName": "",
      "spouseName": "",
      "deleted_at": "2016-04-14 23:36:55",
      "created_at": "2016-04-14 23:21:08",
      "updated_at": "2016-04-14 23:36:55"
    },
    {
      "id": "9",
      "otherID": "NULL",
      "groupID": "1",
      "userID": "NULL",
      "primaryDoc": "0",
      "secondaryDoc": "0",
      "referredByID": "NULL",
      "code": "1",
      "category": "Resident",
      "firstname": "Ambrosio",
      "lastname": "Santos",
      "middlename": "Jose Nilo",
      "nickname": "Nilo",
      "birthdate": "1942-09-18",
      "birthPlace": "Manila",
      "religion": "Roman Catholic",
      "address": "34 M Rodriguez St Philamlife Village Pamplona Dos Las Pinas City",
      "status": "Married",
      "occupation": "businessman",
      "sex": "1",
      "race": "Brown",
      "nationality": "Filipino",
      "height": "",
      "hmoID": "",
      "hmo": "",
      "hmoCode": "",
      "telHome": "(632) 8732273",
      "telOffice": "NULL",
      "telMobile": "09174180510",
      "email": "nilosantos21@yahoo.com",
      "company": "",
      "companyAddress": "",
      "companyContact": "",
      "companyID": "",
      "personNotify": "",
      "personMobile": "",
      "personRelation": "",
      "personAddress": "",
      "insuranceProvider": "",
      "accountVerified": "0",
      "policyNumber": "",
      "imagePath": "NULL",
      "imageMime": "jpg",
      "isPedia": "NULL",
      "fatherName": "",
      "motherName": "",
      "guardianName": "",
      "spouseName": "",
      "deleted_at": "2016-05-03 17:35:35",
      "created_at": "2016-04-14 23:21:09",
      "updated_at": "2016-05-03 17:35:35"
    },
    {
      "id": "10",
      "otherID": "NULL",
      "groupID": "1",
      "userID": "NULL",
      "primaryDoc": "3",
      "secondaryDoc": "1",
      "referredByID": "NULL",
      "code": "10",
      "category": "Resident",
      "firstname": "Lebron",
      "lastname": "James",
      "middlename": "Wade",
      "nickname": "LBJ",
      "birthdate": "1988-01-01",
      "birthPlace": "Manila",
      "religion": "Christian",
      "address": "23 asdf qwerty trewqasdflkjsdn",
      "status": "Single",
      "occupation": "Lovebirds",
      "sex": "1",
      "race": "African America",
      "nationality": "Filipino",
      "height": "6''9",
      "hmoID": "PKPK",
      "hmo": "Philhealth",
      "hmoCode": "PHH",
      "telHome": "02 5555555",
      "telOffice": "NULL",
      "telMobile": "09178888888",
      "email": "james@nba.com",
      "company": "Cavaliers",
      "companyAddress": "Cleveland Ohio",
      "companyContact": "09178881111",
      "companyID": "CLE",
      "personNotify": "mom",
      "personMobile": "09178888181",
      "personRelation": "mom",
      "personAddress": "23 asdf qwerty trewqasdflkjsdn",
      "insuranceProvider": "PKPK",
      "accountVerified": "0",
      "policyNumber": "121212",
      "imagePath": "avatar/99b8982b-9e17-4d3e-ab26-0e2e40e71abe.jpg",
      "imageMime": "jpg",
      "isPedia": "NULL",
      "fatherName": "dad",
      "motherName": "mom",
      "guardianName": "sis",
      "spouseName": "wife",
      "deleted_at": "2016-05-03 17:36:45",
      "created_at": "2016-05-03 00:33:39",
      "updated_at": "2016-05-03 17:36:45"
    },
    {
      "id": "11",
      "otherID": "NULL",
      "groupID": "1",
      "userID": "NULL",
      "primaryDoc": "0",
      "secondaryDoc": "0",
      "referredByID": "NULL",
      "code": "11",
      "category": "Resident",
      "firstname": "blanckg",
      "lastname": "james",
      "middlename": "sdfsdf",
      "nickname": "",
      "birthdate": "2000-01-01",
      "birthPlace": "",
      "religion": "",
      "address": "",
      "status": "Single",
      "occupation": "businessman",
      "sex": "1",
      "race": "",
      "nationality": "",
      "height": "NULL",
      "hmoID": "",
      "hmo": "",
      "hmoCode": "",
      "telHome": "",
      "telOffice": "NULL",
      "telMobile": "123123234",
      "email": "",
      "company": "",
      "companyAddress": "",
      "companyContact": "NULL",
      "companyID": "",
      "personNotify": "",
      "personMobile": "",
      "personRelation": "",
      "personAddress": "",
      "insuranceProvider": "",
      "accountVerified": "0",
      "policyNumber": "",
      "imagePath": "NULL",
      "imageMime": "jpg",
      "isPedia": "NULL",
      "fatherName": "",
      "motherName": "",
      "guardianName": "",
      "spouseName": "",
      "deleted_at": "2016-05-03 17:54:50",
      "created_at": "2016-05-03 17:49:45",
      "updated_at": "2016-05-03 17:54:50"
    }
  ],
  "peCategories": [
    {
      "id": "1",
      "value": "",
      "deleted_at": "2016-03-28 22:35:18",
      "created_at": "2016-03-22 21:21:09",
      "updated_at": "2016-03-28 22:35:18"
    },
    {
      "id": "2",
      "value": "Physical Exam",
      "deleted_at": "NULL",
      "created_at": "2016-03-22 21:21:20",
      "updated_at": "2016-03-22 21:21:20"
    }
  ],
  "peTemplates": [
    {
      "id": "1",
      "text": "<p>VS:</p><p>HEENT:</p><p>Neck:</p><p>Lungs:</p><p>CV:</p><p>GI:</p><p>GU:</p><p>Pulses:</p><p>Lymphs:</p><p>Extremities:</p><p>Neuro:</p>",
      "title": "PE Template",
      "peCategories1ID": "2",
      "peCategories2ID": "NULL",
      "peCategories3ID": "NULL",
      "deleted_at": "NULL",
      "created_at": "2016-03-22 21:20:55",
      "updated_at": "2016-03-28 22:35:29"
    }
  ],
  "postDiagnosis": [
    {
      "id": "6",
      "diagnosisID": "3",
      "followupID": "0",
      "medication": "test",
      "rehabPlan": "test",
      "hospitalCourse": "test",
      "ambulatoryAids": "",
      "physTherapy": "Home",
      "cultWound": "",
      "cultJoint": "",
      "cultBlood": "",
      "labsOther": "",
      "labsHemoglobin": "",
      "labsHematocrit": "",
      "labsPotassium": "",
      "radiographs": "NULL",
      "preparedBy": "NULL",
      "preparedFor": "NULL",
      "relatedImages": "NULL",
      "deleted_at": "NULL",
      "created_at": "2016-03-28 22:55:22",
      "updated_at": "2016-03-28 22:55:22"
    },
    {
      "id": "7",
      "diagnosisID": "5",
      "followupID": "6",
      "medication": "co-amoxiclav 500mg",
      "rehabPlan": "with companion during activity",
      "hospitalCourse": "stable",
      "ambulatoryAids": "Walker",
      "physTherapy": "Home",
      "cultWound": "",
      "cultJoint": "",
      "cultBlood": "",
      "labsOther": "",
      "labsHemoglobin": "23",
      "labsHematocrit": "234",
      "labsPotassium": "23",
      "radiographs": "NULL",
      "preparedBy": "NULL",
      "preparedFor": "NULL",
      "relatedImages": "NULL",
      "deleted_at": "NULL",
      "created_at": "2016-04-03 18:40:20",
      "updated_at": "2016-04-03 18:40:20"
    },
    {
      "id": "8",
      "diagnosisID": "6",
      "followupID": "0",
      "medication": "test",
      "rehabPlan": "test",
      "hospitalCourse": "surgery success",
      "ambulatoryAids": "",
      "physTherapy": "Home",
      "cultWound": "",
      "cultJoint": "",
      "cultBlood": "",
      "labsOther": "",
      "labsHemoglobin": "",
      "labsHematocrit": "",
      "labsPotassium": "",
      "radiographs": "NULL",
      "preparedBy": "NULL",
      "preparedFor": "NULL",
      "relatedImages": "NULL",
      "deleted_at": "NULL",
      "created_at": "2016-04-04 22:44:59",
      "updated_at": "2016-04-04 22:44:59"
    },
    {
      "id": "9",
      "diagnosisID": "7",
      "followupID": "0",
      "medication": "test",
      "rehabPlan": "test",
      "hospitalCourse": "test",
      "ambulatoryAids": "",
      "physTherapy": "Home",
      "cultWound": "",
      "cultJoint": "",
      "cultBlood": "",
      "labsOther": "",
      "labsHemoglobin": "",
      "labsHematocrit": "",
      "labsPotassium": "",
      "radiographs": "NULL",
      "preparedBy": "NULL",
      "preparedFor": "NULL",
      "relatedImages": "NULL",
      "deleted_at": "2016-04-05 00:05:26",
      "created_at": "2016-04-04 23:44:51",
      "updated_at": "2016-04-05 00:05:26"
    },
    {
      "id": "10",
      "diagnosisID": "10",
      "followupID": "22",
      "medication": "asdfsdf",
      "rehabPlan": "1232341",
      "hospitalCourse": "asdfasdf",
      "ambulatoryAids": "",
      "physTherapy": "Home",
      "cultWound": "",
      "cultJoint": "",
      "cultBlood": "",
      "labsOther": "",
      "labsHemoglobin": "",
      "labsHematocrit": "",
      "labsPotassium": "",
      "radiographs": "NULL",
      "preparedBy": "NULL",
      "preparedFor": "NULL",
      "relatedImages": "NULL",
      "deleted_at": "NULL",
      "created_at": "2016-05-03 00:55:15",
      "updated_at": "2016-05-03 00:55:15"
    }
  ],
  "prescriptions": [],
  "procedureCategories": [],
  "procedureCpts": [
    {
      "id": "1",
      "procedureID": "1",
      "cptID": "599",
      "deleted_at": "NULL",
      "created_at": "2016-03-28 19:00:17",
      "updated_at": "2016-03-28 19:00:17"
    },
    {
      "id": "2",
      "procedureID": "1",
      "cptID": "585",
      "deleted_at": "NULL",
      "created_at": "2016-03-28 19:00:17",
      "updated_at": "2016-03-28 19:00:17"
    },
    {
      "id": "3",
      "procedureID": "1",
      "cptID": "581",
      "deleted_at": "NULL",
      "created_at": "2016-03-28 19:00:17",
      "updated_at": "2016-03-28 19:00:17"
    },
    {
      "id": "4",
      "procedureID": "5",
      "cptID": "529",
      "deleted_at": "NULL",
      "created_at": "2016-05-03 00:44:34",
      "updated_at": "2016-05-03 00:44:34"
    }
  ],
  "procedureDoctors": [
    {
      "id": "9",
      "procedureID": "1",
      "doctorID": "3",
      "role": "surgeon1",
      "deleted_at": "NULL",
      "created_at": "2016-03-31 00:49:32",
      "updated_at": "2016-03-31 00:49:32"
    },
    {
      "id": "10",
      "procedureID": "1",
      "doctorID": "0",
      "role": "surgeon2",
      "deleted_at": "NULL",
      "created_at": "2016-03-31 00:49:32",
      "updated_at": "2016-03-31 00:49:32"
    },
    {
      "id": "11",
      "procedureID": "1",
      "doctorID": "0",
      "role": "surgeon3",
      "deleted_at": "NULL",
      "created_at": "2016-03-31 00:49:32",
      "updated_at": "2016-03-31 00:49:32"
    },
    {
      "id": "12",
      "procedureID": "1",
      "doctorID": "0",
      "role": "anesthes",
      "deleted_at": "NULL",
      "created_at": "2016-03-31 00:49:32",
      "updated_at": "2016-03-31 00:49:32"
    },
    {
      "id": "13",
      "procedureID": "2",
      "doctorID": "0",
      "role": "surgeon1",
      "deleted_at": "NULL",
      "created_at": "2016-04-03 18:37:24",
      "updated_at": "2016-04-03 18:37:24"
    },
    {
      "id": "14",
      "procedureID": "2",
      "doctorID": "0",
      "role": "surgeon2",
      "deleted_at": "NULL",
      "created_at": "2016-04-03 18:37:24",
      "updated_at": "2016-04-03 18:37:24"
    },
    {
      "id": "15",
      "procedureID": "2",
      "doctorID": "0",
      "role": "surgeon3",
      "deleted_at": "NULL",
      "created_at": "2016-04-03 18:37:24",
      "updated_at": "2016-04-03 18:37:24"
    },
    {
      "id": "16",
      "procedureID": "2",
      "doctorID": "0",
      "role": "anesthes",
      "deleted_at": "NULL",
      "created_at": "2016-04-03 18:37:24",
      "updated_at": "2016-04-03 18:37:24"
    },
    {
      "id": "17",
      "procedureID": "3",
      "doctorID": "2",
      "role": "surgeon1",
      "deleted_at": "NULL",
      "created_at": "2016-04-04 18:18:29",
      "updated_at": "2016-04-04 18:18:29"
    },
    {
      "id": "18",
      "procedureID": "3",
      "doctorID": "3",
      "role": "surgeon2",
      "deleted_at": "NULL",
      "created_at": "2016-04-04 18:18:29",
      "updated_at": "2016-04-04 18:18:29"
    },
    {
      "id": "19",
      "procedureID": "3",
      "doctorID": "0",
      "role": "surgeon3",
      "deleted_at": "NULL",
      "created_at": "2016-04-04 18:18:29",
      "updated_at": "2016-04-04 18:18:29"
    },
    {
      "id": "20",
      "procedureID": "3",
      "doctorID": "2",
      "role": "anesthes",
      "deleted_at": "NULL",
      "created_at": "2016-04-04 18:18:29",
      "updated_at": "2016-04-04 18:18:29"
    },
    {
      "id": "21",
      "procedureID": "4",
      "doctorID": "0",
      "role": "surgeon1",
      "deleted_at": "NULL",
      "created_at": "2016-04-04 18:19:19",
      "updated_at": "2016-04-04 18:19:19"
    },
    {
      "id": "22",
      "procedureID": "4",
      "doctorID": "0",
      "role": "surgeon2",
      "deleted_at": "NULL",
      "created_at": "2016-04-04 18:19:19",
      "updated_at": "2016-04-04 18:19:19"
    },
    {
      "id": "23",
      "procedureID": "4",
      "doctorID": "0",
      "role": "surgeon3",
      "deleted_at": "NULL",
      "created_at": "2016-04-04 18:19:19",
      "updated_at": "2016-04-04 18:19:19"
    },
    {
      "id": "24",
      "procedureID": "4",
      "doctorID": "0",
      "role": "anesthes",
      "deleted_at": "NULL",
      "created_at": "2016-04-04 18:19:19",
      "updated_at": "2016-04-04 18:19:19"
    },
    {
      "id": "25",
      "procedureID": "5",
      "doctorID": "0",
      "role": "surgeon1",
      "deleted_at": "NULL",
      "created_at": "2016-05-03 00:44:34",
      "updated_at": "2016-05-03 00:44:34"
    },
    {
      "id": "26",
      "procedureID": "5",
      "doctorID": "0",
      "role": "surgeon2",
      "deleted_at": "NULL",
      "created_at": "2016-05-03 00:44:34",
      "updated_at": "2016-05-03 00:44:34"
    },
    {
      "id": "27",
      "procedureID": "5",
      "doctorID": "0",
      "role": "surgeon3",
      "deleted_at": "NULL",
      "created_at": "2016-05-03 00:44:34",
      "updated_at": "2016-05-03 00:44:34"
    },
    {
      "id": "28",
      "procedureID": "5",
      "doctorID": "0",
      "role": "anesthes",
      "deleted_at": "NULL",
      "created_at": "2016-05-03 00:44:34",
      "updated_at": "2016-05-03 00:44:34"
    }
  ],
  "procedureTemplates": [],
  "procedures": [
    {
      "id": "1",
      "diagnosisID": "3",
      "date": "2016-04-04",
      "position": "beach chair",
      "findings": "swollen tendons and ligaments",
      "anesthesia": "regional",
      "bloodLoss": "< 500 ml",
      "timeStart": "10:00:00",
      "timeEnd": "11:30:00",
      "implants": "none",
      "antibiotics": "co-amoxiclav 500mg 1-0-1",
      "transfusion": "none",
      "proDescription": "<p><span style=color: rgb(51",
      "proName": "51",
      "emergencyOrElective": "51); font-family: Roboto",
      "pay": "sans-serif; font-size: 12px; line-height: 18px;>steroid injection in my wrist and wore a brace to immobilize the wrist and thumb</span><br></p>",
      "leadSurgeon": "de quervain tenosynovitis release",
      "otherDoctors": "elective",
      "deleted_at": "hmo",
      "created_at": "2",
      "updated_at": ""
    },
    {
      "id": "2",
      "diagnosisID": "5",
      "date": "2016-04-04",
      "position": "beach chair",
      "findings": "",
      "anesthesia": "general",
      "bloodLoss": "< 500 ml",
      "timeStart": "10:30:00",
      "timeEnd": "11:00:00",
      "implants": "",
      "antibiotics": "",
      "transfusion": "",
      "proDescription": "<p>test</p>",
      "proName": "test",
      "emergencyOrElective": "emergency",
      "pay": "charity",
      "leadSurgeon": "1",
      "otherDoctors": "",
      "deleted_at": "NULL",
      "created_at": "2016-04-03 18:37:24",
      "updated_at": "2016-04-03 18:37:24"
    },
    {
      "id": "3",
      "diagnosisID": "6",
      "date": "2016-04-07",
      "position": "NULL",
      "findings": "",
      "anesthesia": "NULL",
      "bloodLoss": "NULL",
      "timeStart": "10:15:00",
      "timeEnd": "10:45:00",
      "implants": "",
      "antibiotics": "",
      "transfusion": "",
      "proDescription": "<p>test</p>",
      "proName": "test",
      "emergencyOrElective": "emergency",
      "pay": "hmo",
      "leadSurgeon": "1",
      "otherDoctors": "JPI",
      "deleted_at": "NULL",
      "created_at": "2016-04-04 18:18:29",
      "updated_at": "2016-04-04 18:18:29"
    },
    {
      "id": "4",
      "diagnosisID": "3",
      "date": "2016-04-07",
      "position": "NULL",
      "findings": "",
      "anesthesia": "NULL",
      "bloodLoss": "NULL",
      "timeStart": "10:15:00",
      "timeEnd": "10:45:00",
      "implants": "",
      "antibiotics": "",
      "transfusion": "",
      "proDescription": "<p><br></p>",
      "proName": "test",
      "emergencyOrElective": "emergency",
      "pay": "insurance",
      "leadSurgeon": "1",
      "otherDoctors": "",
      "deleted_at": "NULL",
      "created_at": "2016-04-04 18:19:19",
      "updated_at": "2016-04-04 18:19:19"
    },
    {
      "id": "5",
      "diagnosisID": "10",
      "date": "2016-05-03",
      "position": "NULL",
      "findings": "",
      "anesthesia": "NULL",
      "bloodLoss": "NULL",
      "timeStart": "16:45:00",
      "timeEnd": "05:15:00",
      "implants": "",
      "antibiotics": "",
      "transfusion": "",
      "proDescription": "<p>demo&nbsp;&nbsp;&nbsp;&nbsp;</p>",
      "proName": "demo",
      "emergencyOrElective": "emergency",
      "pay": "charity",
      "leadSurgeon": "3",
      "otherDoctors": "",
      "deleted_at": "NULL",
      "created_at": "2016-05-03 00:44:34",
      "updated_at": "2016-05-03 00:44:34"
    }
  ],
  "staff": [
    {
      "id": "1",
      "groupID": "1",
      "patientID": "NULL",
      "userID": "NULL",
      "firstname": "Gerald",
      "middlename": "Benosa",
      "lastname": "Montemayor",
      "nameSuffix": "",
      "birthdate": "1984-03-24",
      "sex": "1",
      "status": "Single",
      "address": "23 Santo Cristo Paranaque City",
      "type": "NULL",
      "phone1": "09124477111",
      "phone2": "",
      "position": "Senior Nurse",
      "email": "Montemayor21@yahoo.com",
      "imagePath": "NULL",
      "imageMime": "jpg",
      "allowAsPatient": "0",
      "schedule": "NULL",
      "deleted_at": "NULL",
      "created_at": "2016-03-22 21:06:41",
      "updated_at": "2016-03-27 18:07:48"
    },
    {
      "id": "2",
      "groupID": "1",
      "patientID": "NULL",
      "userID": "NULL",
      "firstname": "Liza",
      "middlename": "Delara",
      "lastname": "Fernandez",
      "nameSuffix": "",
      "birthdate": "1986-08-21",
      "sex": "0",
      "status": "Single",
      "address": "19 San Andres Bukid Manila",
      "type": "NULL",
      "phone1": "09144555115",
      "phone2": "",
      "position": "Junior Nurse",
      "email": "Fernliz_89@hotmail.com",
      "imagePath": "NULL",
      "imageMime": "jpg",
      "allowAsPatient": "0",
      "schedule": "NULL",
      "deleted_at": "NULL",
      "created_at": "2016-03-22 21:09:24",
      "updated_at": "2016-03-27 18:07:48"
    }
  ],
  "tableLogger": [],
  "userAccessLevel": [],
  "users": [
    {
      "id": "12",
      "groupID": "1",
      "userAccessLevelID": "5",
      "username": "atadmin",
      "password": "$2y$10$d0GwE8xelZZM41OYulifUuy4ZjbmEbCmhf/71HK5hj2OpJza6MqUO",
      "email": "atadmin@ascendant.com.ph",
      "userType": "",
      "failedLogin": "0",
      "hashCode": "",
      "peerID": "NULL",
      "emailVerified": "1",
      "accountVerified": "1",
      "active": "1",
      "online": "1",
      "remember_token": "BG1nAC3tkcDtbWWVPzsmkZQsIVngKWDNIb6JsCE1fDoeXShC3tBReeuZGdtR",
      "deleted_at": "NULL",
      "created_at": "0000-00-00 00:00:00",
      "updated_at": "2016-08-16 18:14:33"
    },
    {
      "id": "23",
      "groupID": "1",
      "userAccessLevelID": "1",
      "username": "nurse1",
      "password": "$2y$10$DR72A9C50iBDS3jiYI5TX.az9f1zGvZdheVUUmNbxPZjwUQR2zKka",
      "email": "NULL",
      "userType": "nurse",
      "failedLogin": "NULL",
      "hashCode": "NULL",
      "peerID": "NULL",
      "emailVerified": "NULL",
      "accountVerified": "NULL",
      "active": "1",
      "online": "0",
      "remember_token": "fMEKMbovadzvjYAdhE4YXLPcICrFEgvsFuIJg5ytQWLYdTP0W3uw79SAVzYh",
      "deleted_at": "NULL",
      "created_at": "2016-03-20 23:48:03",
      "updated_at": "2016-04-03 17:38:21"
    },
    {
      "id": "24",
      "groupID": "1",
      "userAccessLevelID": "1",
      "username": "nurse2",
      "password": "$2y$10$t7zeeJmaFoRFFRn9.5zm8OJ2JGsdqZjkxeVXN.3jUNBOQdTY/ZaA6",
      "email": "NULL",
      "userType": "nurse",
      "failedLogin": "NULL",
      "hashCode": "NULL",
      "peerID": "NULL",
      "emailVerified": "NULL",
      "accountVerified": "NULL",
      "active": "1",
      "online": "0",
      "remember_token": "rHALsb2K5c5IvdNv2fcLiPncHUR4xXp0mOy2A5dlTvfb3anoGFNsEPvgrg0d",
      "deleted_at": "NULL",
      "created_at": "2016-03-20 23:48:27",
      "updated_at": "2016-03-23 19:30:54"
    },
    {
      "id": "25",
      "groupID": "1",
      "userAccessLevelID": "3",
      "username": "doctor1",
      "password": "$2y$10$BhUlINJeCNDERgzHnKPfqOc0bJibarg8jpBqMk97.Nopqver3SQbm",
      "email": "NULL",
      "userType": "doctor",
      "failedLogin": "NULL",
      "hashCode": "NULL",
      "peerID": "NULL",
      "emailVerified": 1,
      "accountVerified": 1,
      "active": "1",
      "online": "0",
      "remember_token": "CIDnHQMJC3KPegPkmq65d88JskNdqgBLC89XN9josHZPs4eO5IQ079V9EhkW",
      "deleted_at": "NULL",
      "created_at": "2016-03-20 23:48:54",
      "updated_at": "2016-03-28 01:31:48"
    },
    {
      "id": "26",
      "groupID": "1",
      "userAccessLevelID": "3",
      "username": "BTG",
      "password": "$2y$10$t.gxXRnJOKvvYe8GaDOc.uNZqYbQGxud0a.LP1vzzjLLCVIUF2Kxq",
      "email": "NULL",
      "userType": "doctor",
      "failedLogin": "NULL",
      "hashCode": "NULL",
      "peerID": "NULL",
      "emailVerified": 1,
      "accountVerified": 1,
      "active": "1",
      "online": "0",
      "remember_token": "C71aR2fDEtSgstcy534sWWRfkuzHWDxJOjv4LX5BTj9h2fVJJRxsi98C8FbB",
      "deleted_at": "NULL",
      "created_at": "2016-03-22 21:14:20",
      "updated_at": "2016-04-01 00:27:08"
    },
    {
      "id": "27",
      "groupID": "1",
      "userAccessLevelID": "1",
      "username": "GVY",
      "password": "$2y$10$QgYqMbqchamKV6znqFGtKunFlVM0hVfqz345Fm.j4w3v676UfQVJ6",
      "email": "NULL",
      "userType": "nurse",
      "failedLogin": "NULL",
      "hashCode": "NULL",
      "peerID": "NULL",
      "emailVerified": "NULL",
      "accountVerified": "NULL",
      "active": "1",
      "online": "0",
      "remember_token": "YLnZHZHzicz5qDFlcwIdUMe8Ng4dS7otGHy25kztkD0hU4hCDK3C3BXoWWpQ",
      "deleted_at": "NULL",
      "created_at": "2016-03-28 01:37:58",
      "updated_at": "2016-03-28 01:39:33"
    },
    {
      "id": "28",
      "groupID": "1",
      "userAccessLevelID": "3",
      "username": "RAJ",
      "password": "$2y$10$4pxCusIU4QcqphAplJIejeZsxi3HFFARznXhvvy6g/0aqUryMNibG",
      "email": "NULL",
      "userType": "doctor",
      "failedLogin": "NULL",
      "hashCode": "NULL",
      "peerID": "NULL",
      "emailVerified": 1,
      "accountVerified": 1,
      "active": "1",
      "online": "0",
      "remember_token": "zWX7MuG0tXijCkZpwfTnDxa6ynm8bj11sbPPPgqX7nOQkuqjaPWW6hOnYXuy",
      "deleted_at": "NULL",
      "created_at": "2016-03-28 16:48:20",
      "updated_at": "2016-03-28 19:25:28"
    },
    {
      "id": "29",
      "groupID": "1",
      "userAccessLevelID": "3",
      "username": "VDD",
      "password": "$2y$10$NHyydskLV08xBQ9xmpINT.XYfKifVecUhxoUYlMfsgnN9uBGlekeu",
      "email": "NULL",
      "userType": "doctor",
      "failedLogin": "NULL",
      "hashCode": "NULL",
      "peerID": "NULL",
      "emailVerified": 1,
      "accountVerified": 1,
      "active": "1",
      "online": "0",
      "remember_token": "rR83v4GqKpiNzu97FEOopWWSDC7v6D1egqIJB3qMcKtHQqmYB6TXPEY0iUse",
      "deleted_at": "NULL",
      "created_at": "2016-03-28 16:49:17",
      "updated_at": "2016-08-15 23:38:55"
    },
    {
      "id": "30",
      "groupID": "1",
      "userAccessLevelID": "3",
      "username": "keno",
      "password": "$2y$10$/IJQRtqJPNbUbxe6qFXraOVwxOHvoYvBXszkyfx9H6bTwEeQUDjnK",
      "email": "NULL",
      "userType": "",
      "failedLogin": "NULL",
      "hashCode": "NULL",
      "peerID": "NULL",
      "emailVerified": "NULL",
      "accountVerified": "NULL",
      "active": "1",
      "online": "1",
      "remember_token": "oU3A54PFrPVEyarCMDOXT6el3azqQWDnra7pjObSdrAspIqZwvaGwbWLaGrz",
      "deleted_at": "NULL",
      "created_at": "2016-04-03 22:46:14",
      "updated_at": "2016-05-23 00:43:28"
    },
    {
      "id": "31",
      "groupID": "1",
      "userAccessLevelID": "4",
      "username": "grace",
      "password": "$2y$10$Mf383zHGGSYbF8DGp9QTre2fJKQs/RQM59j.nHIPiOz2ljjgCbp4.",
      "email": "NULL",
      "userType": "",
      "failedLogin": "NULL",
      "hashCode": "NULL",
      "peerID": "NULL",
      "emailVerified": "NULL",
      "accountVerified": "NULL",
      "active": "1",
      "online": "1",
      "remember_token": "rjE8e2eCyCzluC4l30x5AjkrTGkMKDFK1A73A9tT4NYygHQ3RQmRkCWsudNz",
      "deleted_at": "NULL",
      "created_at": "2016-04-03 22:52:40",
      "updated_at": "2016-04-04 00:21:57"
    },
    {
      "id": "32",
      "groupID": "1",
      "userAccessLevelID": "4",
      "username": "Keeno",
      "password": "$2y$10$PBg1PzUQ1HooegZjsENc9Oxr4vp2JPMh8gqXvgDRSg0gg0S2Zcq1.",
      "email": "NULL",
      "userType": "",
      "failedLogin": "NULL",
      "hashCode": "NULL",
      "peerID": "NULL",
      "emailVerified": "NULL",
      "accountVerified": "NULL",
      "active": "1",
      "online": "0",
      "remember_token": "UBcfzz0Xk18nZoWmHkMzdweKzqfVMxV1R7DEKo9Tarl6hF2Wcwr4sAyydT1a",
      "deleted_at": "NULL",
      "created_at": "2016-05-04 22:10:32",
      "updated_at": "2016-05-04 22:11:07"
    }
  ],
  "vaccineRecords": [],
  "vaccines": []
}
